In [1]:
!pip install fake_useragent

Collecting fake_useragent
  Downloading fake_useragent-2.0.3-py3-none-any.whl.metadata (17 kB)
Downloading fake_useragent-2.0.3-py3-none-any.whl (201 kB)
Installing collected packages: fake_useragent
Successfully installed fake_useragent-2.0.3

[notice] A new release of pip is available: 24.2 -> 25.0
[notice] To update, run: python3 -m pip install --upgrade pip

In [4]:
from fake_useragent import UserAgent

def set_header() -> dict[str, str]:
    return {
        "User-Agent": UserAgent().random,
        "Accept-Language": "ko-KR,ko;q=0.8,en-US;q=0.5,en;q=0.3"
    }

import time
import random

def crawling_waiting_time() -> None:
    return time.sleep(random.randint(1, 3))

import requests
from bs4 import BeautifulSoup

def check_last_page(url):
    response = requests.get(url, headers=set_header())
    response.raise_for_status()
    if response.status_code == 200:
        return response.text
        # soup = BeautifulSoup(response.text, 'html.parser')
        # page = soup.find('div', class_='product-list-paging')
        # return int(page['data-total'])
    return ''

In [ ]:
r = check_last_page('https://link.coupang.com/a/cdqh0M')
r

'<!doctype html>\n<html lang="ko">\n  <head>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />\n    <title></title>\n    <link rel="shortcut icon" href="//image9.coupangcdn.com/image/coupang/favicon/v2/favicon.ico" type="image/x-icon" />\n    <link rel="apple-touch-icon-precomposed" href="//image6.coupangcdn.com/image/coupang/favicon/v2/favicon_256x256.ico" />\n    <style type="text/css">\n    html,body {\n    padding: 0;\n    margin: 0;\n    height: 100%;\n    }\n    body {\n        width: 100%;\n        height: 100%;\n        background-image: url(\'//img1a.coupangcdn.com/image/landing_images/landing_bg_20240131.png\');\n        background-size: contain;\n        background-repeat: no-repeat;\n        font-family: "Apple SD Gothic Neo", "SF Pro Display", "Noto Sans KR", "Roboto", sans-serif;\n    }\n    .redirect-section {\n        position: fixed;\n        width: 100%;\n        box-sizing: border-box;\n        padding: 0px 16px;\n        left: 0;\n        bottom: 0;\n    }\n    .redirect-section .header-text {\n        color: #212B36;\n        font-size: 30px;\n        font-weight: 700;\n        line-height: 36px;\n        letter-spacing: 0em;\n        text-align: left;\n        margin-bottom: 8px;\n    }\n    .redirect-section .tip-text {\n        font-size: 16px;\n        font-weight: 400;\n        line-height: 19px;\n        letter-spacing: 0em;\n        color: #637381;\n    }\n    .redirect-section .btn-bg {\n        display: block;\n        width: 100%;\n        padding: 12px 0;\n        border: 0 none;\n        border-radius: 4px;\n        background-color: #346AFF;\n        font-size: 16px;\n        line-height: 20px;\n        text-align: center;\n        color: #fff;\n        text-decoration: none;\n        font-weight: 700;\n        margin-bottom: 20px;\n    }\n    .redirect-section .btn-bg.low-priority {\n        border: 0 none;\n        background-color: #fff;\n        color: #346AFF;\n        margin-bottom: 44px;\n        line-height: 0;\n    }\n</style>\n    <script src="//asset2.coupangcdn.com/customjs/coupang-web-log/1.3.2/web-log.umd.min.js" type="text/javascript"></script>\n    <script type="text/javascript">\n      CoupangWebLog.init({\n        \'platform\': \'mweb\',\n        \'service\': \'coupang\',\n        \'mode\': \'production\',\n        \'useAutoSendPageViewLog\': false\n      });\n      var redirectWebUrl = \'https\\x3A\\x2F\\x2Fm\\x2Ecoupang\\x2Ecom\\x2Fnm\\x2Fsearch\\x3Fq\\x3D\\x25EA\\x25B7\\x25B8\\x25EB\\x25A1\\x259C\\x25EB\\x25B8\\x258C\\x25C2\\x25A0\\x2520CLANE\\x2520ARGYLE\\x2520SLEEVE\\x2520KNIT\\x5F\\x25EB\\x25B2\\x25A0\\x25EC\\x259D\\x25B4\\x25EC\\x25A7\\x2580\\x26src\\x3D1139000\\x26spec\\x3D10799999\\x26addtag\\x3D200\\x26ctag\\x3D\\x25EA\\x25B7\\x25B8\\x25EB\\x25A1\\x259C\\x25EB\\x25B8\\x258C\\x25C2\\x25A0\\x2520CLANE\\x2520ARGYLE\\x2520SLEEVE\\x2520KNIT\\x5F\\x25EB\\x25B2\\x25A0\\x25EC\\x259D\\x25B4\\x25EC\\x25A7\\x2580\\x26lptag\\x3DAF8709913\\x26itime\\x3D20250207164202\\x26pageType\\x3DSEARCH\\x26pageValue\\x3D\\x25EA\\x25B7\\x25B8\\x25EB\\x25A1\\x259C\\x25EB\\x25B8\\x258C\\x25C2\\x25A0\\x2520CLANE\\x2520ARGYLE\\x2520SLEEVE\\x2520KNIT\\x5F\\x25EB\\x25B2\\x25A0\\x25EC\\x259D\\x25B4\\x25EC\\x25A7\\x2580\\x26wPcid\\x3D17389141222380640104870\\x26wRef\\x3D\\x26wTime\\x3D20250207164202\\x26redirect\\x3Dlanding\\x26traceid\\x3DV0\\x2D181\\x2Dcc53173e5a74b62f\\x26mcid\\x3D61857666c9534e9597e36213b5a22e01\\x26placementid\\x3D\\x26campaignid\\x3D\\x26contentcategory\\x3D\\x26imgsize\\x3D\\x26tsource\\x3D\\x26pageid\\x3D\\x26deviceid\\x3D\\x26token\\x3D\\x26contenttype\\x3D\\x26subid\\x3D\\x26impressionid\\x3D\\x26campaigntype\\x3D\\x26requestid\\x3D\\x26contentkeyword\\x3D\\x26subparam\\x3D\';\n      function getPCId() {\n        var cookieValue = null;\n        var pcIdKey = \'PCID\';\n        if (document.cookie && document.cookie != \'\') {\n            var cookies = document.cookie.split(\';\');\n            for ( var i = 0; i < cookies.length; i++) {\n                var cookie = cookies[i].trim();\n                if (cookie.substring(0, pcIdKey.length + 1) == (pcIdKey + \'=\')) {\n                    cookieValue = decodeURIComponent(cookie.substring(pcIdKey.length + 1));\n                    break;\n                }\n            }\n        }\n        return cookieValue;\n      }\n      var pcid = getPCId();\n\n      function weblogPublish(eventName, targetLocation, targetUri, landingType, mcid) {\n        CoupangWebLog.submit({\n            meta: {\n                \'schemaId\': 10372,\n                \'schemaVersion\': 8\n            },\n            data: {\n                \'logCategory\': \'campaign\',\n                \'logType\': \'landing\',\n                \'domain\': \'landing\',\n                \'pageName\': \'landing_bridge_page\',\n                \'landingType\': landingType,\n                \'mcid\': mcid,\n                \'eventName\': eventName,\n                \'targetLocation\': targetLocation,\n                \'targetUri\': targetUri,\n                \'isAppInstall\' : \'NONE\'\n            }\n        });\n      }\n      function newLandingPageClickWeblogPublish(buttonType) {\n        CoupangWebLog.submit({\n              meta: {\n                  \'schemaId\': 13818,\n                  \'schemaVersion\': 1\n              },\n              data: {\n                  \'logCategory\': \'event\',\n                  \'logType\': \'click\',\n                  \'domain\': \'landing\',\n                  \'pageName\': \'landing_bridge_page\',\n                  \'eventName\': \'landing_bridge_page_cta_click\',\n                  \'wTrackId\': pcid + "_" + Date.now(),\n                  \'wEntrySource\': redirectWebUrl,\n                  \'buttonType\': buttonType\n              }\n          });\n      }\n      function newLandingPageRedirectAppWeblogPublish(redirectType) {\n        CoupangWebLog.submit({\n            meta: {\n                \'schemaId\': 13067,\n                \'schemaVersion\': 3\n            },\n            data: {\n                \'logType\': \'landing\',\n                \'logCategory\': \'campaign\',\n                \'domain\': \'landing\',\n                \'pageName\': \'landing_bridge_page\',\n                \'eventName\': \'mweb_to_app_redirected\',\n                \'wTrackId\': pcid + "_" + Date.now(),\n                \'wEntrySource\': redirectWebUrl,\n                \'redirectSolution\': \'universalLink\',\n                \'osType\': \'ios\',\n                \'redirectPoint\': \'FE\',\n                \'redirectType\': redirectType\n            }\n        });\n      }\n    </script>\n<script >bazadebezolkohpepadr="450269206"</script><script type="text/javascript" src="https://link.coupang.com/akam/13/1ad692c4"  defer></script></head>\n  <body>\n    <div class="redirect-section">\n    <div class="header-text">쿠팡으로 이동중</div>\n    <div style="margin-bottom: 34px;">\n        <div class="tip-text">더이상 이동하지 않으면</div>\n        <div class="tip-text">직접 이동할 수 있어요</div>\n    </div>\n    <div class="btn-bg" id="goWeb">모바일 웹으로 보기</div>\n    <div class="btn-bg low-priority" id="goApp">쿠팡으로 바로가기</div>\n</div>\n    <script type="text/javascript">\n    var initialTime = new Date().getTime();\n    var appleStoreUrl = \'http\\x3A\\x2F\\x2Fitunes\\x2Eapple\\x2Ecom\\x2Fkr\\x2Fapp\\x2Fkupang\\x2Dcoupang\\x2Fid454434967\\x3Fmt\\x3D8\';\n    var appScheme = \'coupang\\x3A\\x2F\\x2Fmlp\\x3FflowId\\x3D7\\x26enableFlowEngine\\x3DY\\x26fallback\\x3Dcoupang\\x253A\\x252F\\x252Fhome\\x26splitKey\\x3DloginRedirection\\x26trafficType\\x3Dmarketing\\x26rUrl\\x3Dcoupang\\x253A\\x252F\\x252Fsearch\\x253Fq\\x253D\\x2525EA\\x2525B7\\x2525B8\\x2525EB\\x2525A1\\x25259C\\x2525EB\\x2525B8\\x25258C\\x2525C2\\x2525A0\\x252520CLANE\\x252520ARGYLE\\x252520SLEEVE\\x252520KNIT\\x5F\\x2525EB\\x2525B2\\x2525A0\\x2525EC\\x25259D\\x2525B4\\x2525EC\\x2525A7\\x252580\\x2526src\\x253D1139000\\x2526spec\\x253D10799999\\x2526addtag\\x253D200\\x2526ctag\\x253D\\x2525EA\\x2525B7\\x2525B8\\x2525EB\\x2525A1\\x25259C\\x2525EB\\x2525B8\\x25258C\\x2525C2\\x2525A0\\x252520CLANE\\x252520ARGYLE\\x252520SLEEVE\\x252520KNIT\\x5F\\x2525EB\\x2525B2\\x2525A0\\x2525EC\\x25259D\\x2525B4\\x2525EC\\x2525A7\\x252580\\x2526lptag\\x253DAF8709913\\x2526itime\\x253D20250207164202\\x2526pageType\\x253DSEARCH\\x2526pageValue\\x253D\\x2525EA\\x2525B7\\x2525B8\\x2525EB\\x2525A1\\x25259C\\x2525EB\\x2525B8\\x25258C\\x2525C2\\x2525A0\\x252520CLANE\\x252520ARGYLE\\x252520SLEEVE\\x252520KNIT\\x5F\\x2525EB\\x2525B2\\x2525A0\\x2525EC\\x25259D\\x2525B4\\x2525EC\\x2525A7\\x252580\\x2526wPcid\\x253D17389141222380640104870\\x2526wRef\\x253D\\x2526wTime\\x253D20250207164202\\x2526redirect\\x253Dlanding\\x2526traceid\\x253DV0\\x2D181\\x2Dcc53173e5a74b62f\\x2526mcid\\x253D61857666c9534e9597e36213b5a22e01\\x2526placementid\\x253D\\x2526campaignid\\x253D\\x2526contentcategory\\x253D\\x2526imgsize\\x253D\\x2526tsource\\x253D\\x2526pageid\\x253D\\x2526deviceid\\x253D\\x2526token\\x253D\\x2526contenttype\\x253D\\x2526subid\\x253D\\x2526impressionid\\x253D\\x2526campaigntype\\x253D\\x2526requestid\\x253D\\x2526contentkeyword\\x253D\\x2526subparam\\x253D\\x26src\\x3D1139000\\x26spec\\x3D10799999\\x26addtag\\x3D200\\x26ctag\\x3D\\x25EA\\x25B7\\x25B8\\x25EB\\x25A1\\x259C\\x25EB\\x25B8\\x258C\\x25C2\\x25A0\\x2520CLANE\\x2520ARGYLE\\x2520SLEEVE\\x2520KNIT\\x5F\\x25EB\\x25B2\\x25A0\\x25EC\\x259D\\x25B4\\x25EC\\x25A7\\x2580\\x26lptag\\x3DAF8709913\\x26itime\\x3D20250207164202\\x26pageType\\x3DSEARCH\\x26pageValue\\x3D\\x25EA\\x25B7\\x25B8\\x25EB\\x25A1\\x259C\\x25EB\\x25B8\\x258C\\x25C2\\x25A0\\x2520CLANE\\x2520ARGYLE\\x2520SLEEVE\\x2520KNIT\\x5F\\x25EB\\x25B2\\x25A0\\x25EC\\x259D\\x25B4\\x25EC\\x25A7\\x2580\\x26wPcid\\x3D17389141222380640104870\\x26wRef\\x3D\\x26wTime\\x3D20250207164202\\x26redirect\\x3Dlanding\\x26traceid\\x3DV0\\x2D181\\x2Dcc53173e5a74b62f\\x26mcid\\x3D61857666c9534e9597e36213b5a22e01\\x26placementid\\x3D\\x26campaignid\\x3D\\x26contentcategory\\x3D\\x26imgsize\\x3D\\x26tsource\\x3D\\x26pageid\\x3D\\x26deviceid\\x3D\\x26token\\x3D\\x26contenttype\\x3D\\x26subid\\x3D\\x26impressionid\\x3D\\x26campaigntype\\x3D\\x26requestid\\x3D\\x26contentkeyword\\x3D\\x26subparam\\x3D\';\n    var landingType = \'TRACKING_LANDING\';\n    var mcid = \'61857666c9534e9597e36213b5a22e01\';\n    var redirectWebUrl = \'https\\x3A\\x2F\\x2Fm\\x2Ecoupang\\x2Ecom\\x2Fnm\\x2Fsearch\\x3Fq\\x3D\\x25EA\\x25B7\\x25B8\\x25EB\\x25A1\\x259C\\x25EB\\x25B8\\x258C\\x25C2\\x25A0\\x2520CLANE\\x2520ARGYLE\\x2520SLEEVE\\x2520KNIT\\x5F\\x25EB\\x25B2\\x25A0\\x25EC\\x259D\\x25B4\\x25EC\\x25A7\\x2580\\x26src\\x3D1139000\\x26spec\\x3D10799999\\x26addtag\\x3D200\\x26ctag\\x3D\\x25EA\\x25B7\\x25B8\\x25EB\\x25A1\\x259C\\x25EB\\x25B8\\x258C\\x25C2\\x25A0\\x2520CLANE\\x2520ARGYLE\\x2520SLEEVE\\x2520KNIT\\x5F\\x25EB\\x25B2\\x25A0\\x25EC\\x259D\\x25B4\\x25EC\\x25A7\\x2580\\x26lptag\\x3DAF8709913\\x26itime\\x3D20250207164202\\x26pageType\\x3DSEARCH\\x26pageValue\\x3D\\x25EA\\x25B7\\x25B8\\x25EB\\x25A1\\x259C\\x25EB\\x25B8\\x258C\\x25C2\\x25A0\\x2520CLANE\\x2520ARGYLE\\x2520SLEEVE\\x2520KNIT\\x5F\\x25EB\\x25B2\\x25A0\\x25EC\\x259D\\x25B4\\x25EC\\x25A7\\x2580\\x26wPcid\\x3D17389141222380640104870\\x26wRef\\x3D\\x26wTime\\x3D20250207164202\\x26redirect\\x3Dlanding\\x26traceid\\x3DV0\\x2D181\\x2Dcc53173e5a74b62f\\x26mcid\\x3D61857666c9534e9597e36213b5a22e01\\x26placementid\\x3D\\x26campaignid\\x3D\\x26contentcategory\\x3D\\x26imgsize\\x3D\\x26tsource\\x3D\\x26pageid\\x3D\\x26deviceid\\x3D\\x26token\\x3D\\x26contenttype\\x3D\\x26subid\\x3D\\x26impressionid\\x3D\\x26campaigntype\\x3D\\x26requestid\\x3D\\x26contentkeyword\\x3D\\x26subparam\\x3D\';\n\n    weblogPublish(\'landing_bridge_page_view\', \'landing_bridge_page\', \'ios_app_or_web\', landingType, mcid);\n    function goApp() {\n        weblogPublish(\'target_page_launch\', \'ios_app\', appScheme, landingType, mcid);\n        newLandingPageRedirectAppWeblogPublish(\'auto\');\n        location.href = appScheme;\n    }\n    \n    setTimeout(function () {\n      if (new Date().getTime() - initialTime < 1000) {\n        weblogPublish(\'target_page_launch\', \'ios_mweb\', redirectWebUrl, landingType, mcid);\n        location.replace(redirectWebUrl);\n      }\n    }, 500);\n    // 주의!!!! 바로 location.href = appScheme을 하는 경우 간헐적으로 새창 뜰 때 동작하지 않는 경우가 있어 일정 시간 wait 후 app scheme 호출한다.\n    setTimeout(function() {\n      goApp();\n    }, 100);\n\n    document.getElementById(\'goWeb\').addEventListener(\'click\', function handleGoWebClick() {\n        newLandingPageClickWeblogPublish(\'view_on_mobile_web\');\n        location.href = redirectWebUrl;\n    })\n    document.getElementById(\'goApp\').addEventListener(\'click\', function handleGoAppClick() {\n        newLandingPageClickWeblogPublish(\'continue_on_app\');\n        goApp();\n    })\n</script>\n  <noscript><img src="https://link.coupang.com/akam/13/pixel_1ad692c4?a=dD0xOTk5YjFjMjY0MTUwNzgwN2M3OWNhOTBjYjA4NGQzZWI2YTc0OGQyJmpzPW9mZg==" style="visibility: hidden; position: absolute; left: -999px; top: -999px;" /></noscript><script type="text/javascript"  src="/HgzOiwr-ETX3c4ogzleeKVCs_eA/5hz7bJhmYak4Eai9/ai9Y/RSF8/HVQ3Rh8"></script></body>\n</html>'

In [2]:
base_url = "https://rss.blog.naver.com/{name}.xml"
count_url = "https://blog.naver.com/NVisitorgp4Ajax.nhn?blogId={name}"
blogs = [
    ("bcf5qp11", "쇼핑"), # 고풜 (1개씩)
    ("celubdigging", "파트너스활동으로 소정 수익발생"),
    ("dalcome5", "◇궁금해◇"),
    ("dehi61", "파트너스활동으로 소정 수익발생"),
    ("fashionblog-", "방송·연예·패션"),
    ("hkh443", "추천템"),
    ("hprbel1097", "방송/패션"),
    ("hsh6566", "방송아이템"),
    ("jsodnfak", "방송정보"),
    ("phd_choi93", "패션/코디 정보"),
    ("pravas", "TV 속 상품 정보"),
    ("skywhite369", "방송v패션v맛집v제품"),
    ("lzheng", "방송그제품"),
    ("unknown0998", "정보 생활"),
    ("nemo-c", "방송제품정보"),
    # ("skyblue2564", "셀럽아이템"), # 카피0 # 이미지 링크
        # ("moji1122", "셀럽옷장"), # 카피1
        # ("sanand0206", "패션탐구생활"), # 카피2
        
    # ("yangki2346", "방송,제품"), # 댓글형 링크
    # ("agla1", "유용한 아이템"), # 댓글형 링크
    # ("khm8208", "방송아이템"), # 댓글형 링크
    # ("tazsun20", "방송아이템★"), # 댓글형 링크
    # ("mn_uni", "제품정보"), # 댓글형 링크
        
    # ("mrdaddytv", "패션상품정보"), # 저품질
    # ("icis66", "방송아이템"), # 저품질
    # ("smilek17", "방송/코디"), # 저품질
]

In [3]:
def get_visit_count(name):
    import xmltodict
    import requests
    url = f"https://blog.naver.com/NVisitorgp4Ajax.nhn?blogId={name}"
    response = requests.get(url)
    tree = xmltodict.parse(response.text)
    cmax = 0
    for stree in tree["visitorcnts"]["visitorcnt"]:
        # print(int(stree["@cnt"]))
        cmax = max(int(stree["@cnt"]), cmax)        
    return cmax

In [4]:
get_visit_count('shaneangel')

138

In [5]:
import pandas as pd
df = pd.DataFrame([x[0] for x in blogs], columns=['url'])
df

             url
0       bcf5qp11
1   celubdigging
2       dalcome5
3         dehi61
4   fashionblog-
5         hkh443
6     hprbel1097
7        hsh6566
8       jsodnfak
9     phd_choi93
10        pravas
11   skywhite369
12        lzheng
13   unknown0998
14        nemo-c

In [6]:
today = pd.to_datetime('now', utc=True).floor('D').strftime('%y%m%d')
today

'250207'

In [7]:
df['count'] = df['url'].apply(lambda x : get_visit_count(x))

In [8]:
df = df.sort_values('count', ascending=False)
df = df.reset_index(drop=True)
df.to_csv('blog_data/test.csv')
df

             url  count
0         nemo-c   7449
1        hsh6566   4974
2         lzheng   3852
3     phd_choi93   3240
4    skywhite369   2557
5   celubdigging   1683
6       dalcome5   1635
7         hkh443   1462
8     hprbel1097   1179
9         pravas    883
10        dehi61    527
11      bcf5qp11    336
12  fashionblog-    254
13      jsodnfak    195
14   unknown0998    179

In [9]:
def get_rss(name, folder):
    import xmltodict
    import requests
    url = base_url.format(name=name)
    response = requests.get(url)
    tree = xmltodict.parse(response.text)
    # list인 item 내 category가 folder인 목록
    # return tree
    return [{'title':x['title'], 'url':x['guid'], 'date':x['pubDate'], 'tag':x['tag'] if x['tag'] != None else ''} for x in tree['rss']['channel']['item'] if x['category'] == folder]

In [10]:
get_rss("agla1", "유용한 아이템")

[{'title': '최화정 자라 가방 진주 목걸이 선글라스 하트 찍찍이 레몬즙짜개 가글',
  'url': 'https://blog.naver.com/agla1/223751135245',
  'date': 'Fri, 07 Feb 2025 12:02:37 +0900',
  'tag': ''},
 {'title': '최화정 향수 괄사 얼굴 마사지기 석쇠 미니 비닐 투명 지갑 아로마 오일 블러쉬 블러셔',
  'url': 'https://blog.naver.com/agla1/223751060216',
  'date': 'Fri, 07 Feb 2025 11:12:40 +0900',
  'tag': ''},
 {'title': '전참시 연우 패딩 잠바 가방 현실도피자 후드티 옷 필라테스복 소파 쇼파 tv',
  'url': 'https://blog.naver.com/agla1/223747458810',
  'date': 'Tue, 04 Feb 2025 15:58:14 +0900',
  'tag': ''},
 {'title': '냉장고를 부탁해 손석구 토마토즙 레몬즙 시계 셔츠 옷 냉부해',
  'url': 'https://blog.naver.com/agla1/223746586407',
  'date': 'Mon, 03 Feb 2025 21:18:04 +0900',
  'tag': ''},
 {'title': '나혼자산다 김대호 새조개 샤브샤브 육수 여수 제철 유자 간장 소스 매생이 과메기 샤워 가운 염색약 나혼산',
  'url': 'https://blog.naver.com/agla1/223746379813',
  'date': 'Mon, 03 Feb 2025 17:36:08 +0900',
  'tag': ''},
 {'title': '미우새 이상민 한강 라면 기계 끓이는 조리기 이동건 엄마 패딩 고아라 셔츠 옷',
  'url': 'https://blog.naver.com/agla1/223745954402',
  'date': 'Mon, 03 Feb 2025 11:19:54 +0900',
  'tag': ''},
 {'title': '나의 완벽한 비서 8회 한지민 옷 블라우스 원피스 가방 바지 초콜릿 사탕',
  'url': 'https://blog.naver.com/agla1/223739144477',
  'date': 'Sun, 26 Jan 2025 15:17:50 +0900',
  'tag': ''},
 {'title': '전참시 김아영 마스크팩 책상 다도 세트 주전자 화병',
  'url': 'https://blog.naver.com/agla1/223739068927',
  'date': 'Sun, 26 Jan 2025 13:38:15 +0900',
  'tag': ''},
 {'title': '전참시 김아영 옷 무스탕 자켓 가방 백팩 헤드셋 헤드폰 니트 카라티 잠옷',
  'url': 'https://blog.naver.com/agla1/223739001865',
  'date': 'Sun, 26 Jan 2025 12:05:24 +0900',
  'tag': ''},
 {'title': '나의 완벽한 비서 7회 한지민 가방 옷 블라우스 니트 자켓 셋업 정장 7화',
  'url': 'https://blog.naver.com/agla1/223738133787',
  'date': 'Sat, 25 Jan 2025 14:58:08 +0900',
  'tag': ''},
 {'title': '나혼자산다 김대호 빔프로젝터 프로젝트 쇼파 소파 테이블 이주승 강아지 패딩 나혼산',
  'url': 'https://blog.naver.com/agla1/223738079609',
  'date': 'Sat, 25 Jan 2025 13:48:41 +0900',
  'tag': ''},
 {'title': '유퀴즈 김성령 옷 집업 자켓 의상 치마 스커트',
  'url': 'https://blog.naver.com/agla1/223735565217',
  'date': 'Thu, 23 Jan 2025 10:54:54 +0900',
  'tag': ''},
 {'title': '동상이몽 슬리피 김나현 팩 마스크팩 얼굴 코트 이지혜 오프숄더 옷 이현이 자켓',
  'url': 'https://blog.naver.com/agla1/223732896411',
  'date': 'Tue, 21 Jan 2025 16:46:05 +0900',
  'tag': ''},
 {'title': '냉장고를 부탁해 장원영 피스타치오 스프레드 밤꿀 고트 치즈 소금 올리브오일 옷 원피스 냉부해',
  'url': 'https://blog.naver.com/agla1/223731300063',
  'date': 'Mon, 20 Jan 2025 10:00:45 +0900',
  'tag': ''},
 {'title': '전참시 박세리 간장게장 가방 시계 패딩 잠바 맨투맨 옷',
  'url': 'https://blog.naver.com/agla1/223730595744',
  'date': 'Sun, 19 Jan 2025 14:56:07 +0900',
  'tag': ''},
 {'title': '나의 완벽한 비서 6회 한지민 옷 셔츠 블라우스 자켓 가방 귀걸이 잠옷 6화',
  'url': 'https://blog.naver.com/agla1/223730478801',
  'date': 'Sun, 19 Jan 2025 11:45:44 +0900',
  'tag': ''},
 {'title': '나혼자산다 코쿤 수제화 구두 가격 맞춤 동생 코트 자켓 옷 신발 가방 나혼산',
  'url': 'https://blog.naver.com/agla1/223729826871',
  'date': 'Sat, 18 Jan 2025 14:58:42 +0900',
  'tag': ''},
 {'title': '나의 완벽한 비서 한지민 자켓 5회 옷 니트 가방 치마 스커트 5화',
  'url': 'https://blog.naver.com/agla1/223729768250',
  'date': 'Sat, 18 Jan 2025 13:37:11 +0900',
  'tag': ''}]

In [11]:
import pandas as pd
l = []
for x, y in blogs:
    l = l + get_rss(x, y)
df = pd.DataFrame(l)
df

,title,url,date,tag
0,전참시 김아영 화병 홈앤하비 도자기화병 세라믹 인테리어 고리형,https://blog.naver.com/bcf5qp11/223750032612,"Fri, 07 Feb 2025 07:00:00 +0900","전지적참견시점,김아영,홈앤하비,도자기화병,모던인테리어,홈데코,감성인테리어,꽃꽂이,세..."
1,전참시 김아영 다도세트 자사호 전통다기세트 찻잔세트 다도용품,https://blog.naver.com/bcf5qp11/223750015985,"Thu, 06 Feb 2025 19:00:00 +0900","전지적참견시점,김아영,자사호다도세트,전통다도,차도구,보이차,우롱차,홍차,다도용품,찻..."
2,나완비 한지민 바지 짐머만 워시드 실크 벨티드 와이드 레그 팬츠,https://blog.naver.com/bcf5qp11/223748491659,"Thu, 06 Feb 2025 07:00:00 +0900","나의완벽한비서,한지민패션,짐머만팬츠,실크팬츠,벨티드팬츠,와이드레그팬츠,세련된스타일,..."
3,나완비 한지민 커피캔디 코피코 사탕 블리스터 커피맛사탕,https://blog.naver.com/bcf5qp11/223748472288,"Wed, 05 Feb 2025 19:00:00 +0900","나의완벽한비서,한지민,코피코사탕,커피맛사탕,블리스터팩,커피캔디,휴대용간식,무설"
4,전참시 김아영 마스크팩 웰라쥬 리얼 히알루로닉 블루 앰플 마스크,https://blog.naver.com/bcf5qp11/223747241692,"Wed, 05 Feb 2025 07:00:00 +0900","전지적참견시점,김아영마스크팩,웰라쥬,히알루론산마스크팩,보습케어,수분팩,피부탄력,건조..."
...,...,...,...,...
614,오윤아 TV 인생 향수 추천 여름 향수 엑스니힐로 메모 밀러 해리스 커정,https://blog.naver.com/unknown0998/223513096625,"Mon, 15 Jul 2024 10:24:48 +0900","오윤아여름향수,오윤아향수,엑스니힐로,엑스니힐로향수,밀러해리스향수,향수추천템,여름향수..."
615,이해리 부츠 패딩 조선양봉 꿀 거울 도마 (유튜브 속 아이템),https://blog.naver.com/nemo-c/223746366675,"Mon, 03 Feb 2025 17:24:28 +0900","거울,꿀선물,꿀선물세트,꿀,다이슨,다이슨드라이기,딥티크,화장대거울,다이슨드라이어,밤..."
616,전참시 연우 소파 쇼파 테이블 이불 피아노 스탠바이미 집 정보,https://blog.naver.com/nemo-c/223744671354,"Sat, 01 Feb 2025 23:48:01 +0900","이불,쇼파추천,쇼파,소파,패브릭소파,TV,스마트티비,디지털피아노,3인용쇼파,3인소파..."
617,나혼자산다 김대호 사우나 가격은? 가안 홈사우나 (구입링크),https://blog.naver.com/nemo-c/223743708954,"Fri, 31 Jan 2025 22:49:35 +0900","핀란드사우나,사우나스토브,건식사우나,사우나,가정용사우나,찜질방시공,핀란드식사우나,편..."
618,나혼자산다 김대호 사우나 타일 소파 테이블 청소기 빔프로젝터 러그 수납장 조명 문고...,https://blog.naver.com/nemo-c/223738111945,"Sat, 25 Jan 2025 14:30:29 +0900","습식청소기,집인테리어,조명,주택인테리어,인테리어조명,핀란드사우나,자취방꾸미기,1인쇼..."

In [12]:
df['date'] = pd.to_datetime(df['date'])
df

,title,url,date,tag
0,전참시 김아영 화병 홈앤하비 도자기화병 세라믹 인테리어 고리형,https://blog.naver.com/bcf5qp11/223750032612,2025-02-07 07:00:00+09:00,"전지적참견시점,김아영,홈앤하비,도자기화병,모던인테리어,홈데코,감성인테리어,꽃꽂이,세..."
1,전참시 김아영 다도세트 자사호 전통다기세트 찻잔세트 다도용품,https://blog.naver.com/bcf5qp11/223750015985,2025-02-06 19:00:00+09:00,"전지적참견시점,김아영,자사호다도세트,전통다도,차도구,보이차,우롱차,홍차,다도용품,찻..."
2,나완비 한지민 바지 짐머만 워시드 실크 벨티드 와이드 레그 팬츠,https://blog.naver.com/bcf5qp11/223748491659,2025-02-06 07:00:00+09:00,"나의완벽한비서,한지민패션,짐머만팬츠,실크팬츠,벨티드팬츠,와이드레그팬츠,세련된스타일,..."
3,나완비 한지민 커피캔디 코피코 사탕 블리스터 커피맛사탕,https://blog.naver.com/bcf5qp11/223748472288,2025-02-05 19:00:00+09:00,"나의완벽한비서,한지민,코피코사탕,커피맛사탕,블리스터팩,커피캔디,휴대용간식,무설"
4,전참시 김아영 마스크팩 웰라쥬 리얼 히알루로닉 블루 앰플 마스크,https://blog.naver.com/bcf5qp11/223747241692,2025-02-05 07:00:00+09:00,"전지적참견시점,김아영마스크팩,웰라쥬,히알루론산마스크팩,보습케어,수분팩,피부탄력,건조..."
...,...,...,...,...
614,오윤아 TV 인생 향수 추천 여름 향수 엑스니힐로 메모 밀러 해리스 커정,https://blog.naver.com/unknown0998/223513096625,2024-07-15 10:24:48+09:00,"오윤아여름향수,오윤아향수,엑스니힐로,엑스니힐로향수,밀러해리스향수,향수추천템,여름향수..."
615,이해리 부츠 패딩 조선양봉 꿀 거울 도마 (유튜브 속 아이템),https://blog.naver.com/nemo-c/223746366675,2025-02-03 17:24:28+09:00,"거울,꿀선물,꿀선물세트,꿀,다이슨,다이슨드라이기,딥티크,화장대거울,다이슨드라이어,밤..."
616,전참시 연우 소파 쇼파 테이블 이불 피아노 스탠바이미 집 정보,https://blog.naver.com/nemo-c/223744671354,2025-02-01 23:48:01+09:00,"이불,쇼파추천,쇼파,소파,패브릭소파,TV,스마트티비,디지털피아노,3인용쇼파,3인소파..."
617,나혼자산다 김대호 사우나 가격은? 가안 홈사우나 (구입링크),https://blog.naver.com/nemo-c/223743708954,2025-01-31 22:49:35+09:00,"핀란드사우나,사우나스토브,건식사우나,사우나,가정용사우나,찜질방시공,핀란드식사우나,편..."
618,나혼자산다 김대호 사우나 타일 소파 테이블 청소기 빔프로젝터 러그 수납장 조명 문고...,https://blog.naver.com/nemo-c/223738111945,2025-01-25 14:30:29+09:00,"습식청소기,집인테리어,조명,주택인테리어,인테리어조명,핀란드사우나,자취방꾸미기,1인쇼..."

In [13]:
# date 2 days ago from now (date : dtype=datetime64[ns, UTC+09:00] usin np.datetime64
date_2d = pd.to_datetime('now', utc=True)
date_2d_ago = date_2d - pd.DateOffset(days=2)
date_2d_ago = date_2d_ago.floor('D')
df2 = df[df['date'] >= date_2d_ago]
df2.reset_index(drop=True, inplace=True)
df2.to_csv('blog_data/test2.csv')
df2

,title,url,date,tag
0,전참시 김아영 화병 홈앤하비 도자기화병 세라믹 인테리어 고리형,https://blog.naver.com/bcf5qp11/223750032612,2025-02-07 07:00:00+09:00,"전지적참견시점,김아영,홈앤하비,도자기화병,모던인테리어,홈데코,감성인테리어,꽃꽂이,세..."
1,전참시 김아영 다도세트 자사호 전통다기세트 찻잔세트 다도용품,https://blog.naver.com/bcf5qp11/223750015985,2025-02-06 19:00:00+09:00,"전지적참견시점,김아영,자사호다도세트,전통다도,차도구,보이차,우롱차,홍차,다도용품,찻..."
2,나완비 한지민 바지 짐머만 워시드 실크 벨티드 와이드 레그 팬츠,https://blog.naver.com/bcf5qp11/223748491659,2025-02-06 07:00:00+09:00,"나의완벽한비서,한지민패션,짐머만팬츠,실크팬츠,벨티드팬츠,와이드레그팬츠,세련된스타일,..."
3,나완비 한지민 커피캔디 코피코 사탕 블리스터 커피맛사탕,https://blog.naver.com/bcf5qp11/223748472288,2025-02-05 19:00:00+09:00,"나의완벽한비서,한지민,코피코사탕,커피맛사탕,블리스터팩,커피캔디,휴대용간식,무설"
4,강주은 시슬리 화장품 나스 컨실러 쉐도우 팔레트 헉슬리 크림 세럼 거울,https://blog.naver.com/celubdigging/223751391830,2025-02-07 14:53:45+09:00,"강주은,메이크업템,뷰티추천,강주은화장품,50대뷰티,자연스러운메이크업,럭셔리스킨케어,..."
5,강주은 드라이기 돈모 롤빗 브러쉬,https://blog.naver.com/celubdigging/223750065876,2025-02-06 18:06:45+09:00,"강주은,강주은곱슬머리,강주은드라이기,강주은헤어드라이어,강주은롤빗,강주은돈모브러쉬,강..."
6,나솔사계 경리 반팔 니트 미니스커트 정보,https://blog.naver.com/celubdigging/223749999680,2025-02-06 17:09:33+09:00,"나솔사계,나솔사계99화,경리패션,경리아가일니트,경리스커트,그로브,아가일패턴,봄코디,..."
7,이주미 애장템 핸드폰 케이스 샤워가운 자주 파자마 도시락통 멀티스틱 곱창 4색볼펜 ...,https://blog.naver.com/celubdigging/223749797103,2025-02-06 14:21:07+09:00,"이주미,이주미애장템,이주미애장품,이주미핸드폰케이스,이주미신지모루,이주미안경,이주미케..."
8,라디오스타 장도연 오프숄더 니트 코쿤 가디건 박나래 땡땡이 오프숄더 문세윤 꽃무늬 ...,https://blog.naver.com/celubdigging/223748800581,2025-02-05 17:42:57+09:00,"라디오스타장도연니트,라디오스타박나래블라우스,라디오스타코쿤가디건,라디오스타문세윤자켓,..."
9,애라원 두유제조기 신애라 찜기 혈당영양제 병아리콩 혈당측정기,https://blog.naver.com/celubdigging/223748586408,2025-02-05 14:49:22+09:00,"신애라찜기,신애라혈당영양제,신애라두유제조기,애라원혈당측정기,애라원건강템"
10,이현이 유튜브 샤워기 필터 몽클레어 패딩 한강라면 기계 욕실크림,https://blog.naver.com/celubdigging/223748334936,2025-02-05 11:05:45+09:00,"이현이,이현이유튜브,이현이샤워기필터,이현이몽클레어,이현이롱패딩,이현이욕실크림,이현이..."
11,나는솔로 송해나 가디건 이이경 자켓 데프콘 스웨터 티셔츠 그린체크 울재킷 패션 나솔...,https://blog.naver.com/dalcome5/223749106268,2025-02-05 22:57:29+09:00,
12,라디오스타 코쿤 가디건 장도연 니트 오프숄더탑 박나래 블라우스 귀걸이 실크셔츠 문세...,https://blog.naver.com/dalcome5/223749075383,2025-02-05 22:26:18+09:00,
13,유퀴즈 전민철 니트 스웨터 유재석 운동화 스니커즈 옷 패션 279회재방송 정보,https://blog.naver.com/dalcome5/223748978348,2025-02-05 20:46:12+09:00,
14,시슬리 화장품만 쓰는 강주은이 추천하는 헉슬리,https://blog.naver.com/dehi61/223751438018,2025-02-07 15:22:02+09:00,"강주은,메이크업템,뷰티추천,강주은화장품,50대뷰티,자연스러운메이크업,럭셔리스킨케어,..."
15,강주은 charis 드라이기 2만원대 밖에 안하네요,https://blog.naver.com/dehi61/223750068994,2025-02-06 18:09:52+09:00,"강주은,강주은드라이기,가성비드라이기,강주은롤빗,돈모브러쉬,헤어관리,스타일링팁,볼륨드라이"
16,나솔사계 99화 경리 패션 찾았어요,https://blog.naver.com/dehi61/223750003834,2025-02-06 17:12:59+09:00,"나솔사계,나솔사계99화,경리패션,경리아가일니트,경리스커트,그로브,아가일패턴,봄코디,..."
17,이주미 자주 파자마 물티슈 파우치는 더 저렴한거 추천드림,https://blog.naver.com/dehi61/223749820907,2025-02-06 14:40:52+09:00,"이주미애장템,이주미추천템,이주미돈모브러쉬,이주미신지모루,이주미도시락,이주미파자마,이..."
18,라디오스타 900회 특집 박나래 땡땡이 옷 ZARA 였음,https://blog.naver.com/dehi61/223748806244,2025-02-05 17:47:45+09:00,"라디오스타장도연니트,라디오스타박나래블라우스,라디오스타코쿤가디건,라디오스타문세윤자켓,..."
19,신애라 두유 병아리콩 만들어먹고 50kg 유지?,https://blog.naver.com/dehi61/223748591989,2025-02-05 14:53:52+09:00,"신애라찜기,신애라혈당영양제,신애라두유제조기,애라원혈당측정기,애라원건강템"
20,이현이 몽클레어 패딩 찾았어요!,https://blog.naver.com/dehi61/223748343474,2025-02-05 11:11:51+09:00,"이현이유튜브,샤워기필터,한강라면기계,몽클레어패딩,살림초보,PPL아님,방송속템,이현이..."
21,유나 클렌저 괄사 향수 목마사지기 헤어브러쉬 빗 ITZY 있지 유난히빛이나 왓츠인마...,https://blog.naver.com/hkh443/223751349466,2025-02-07 14:27:29+09:00,"유나,있지유나,유나아이템,유나클렌저,유나향수,유나괄사,유나목마사지기,유나헤어브러쉬,유나빗"
22,이현이 샤워필터 연수기 욕실정리 한강라면기계 제조기 아이템 정보,https://blog.naver.com/hkh443/223751263683,2025-02-07 13:31:00+09:00,"이현이,이현이아이템,이현이샤워필터,이현이연수기,이현이한강라면,이현이라면기계,이현이라..."
23,애라원 신애라 잡곡 쌀통 밥솥 찜기 두유제조기 에어프라이어 솔잎 추출물 건강식품 주...,https://blog.naver.com/hkh443/223751217913,2025-02-07 13:00:41+09:00,"애라원,애라원주방용품,신애라,신애라주방용품,애라원쌀통,애라원밥솥,애라원찜기,애라원두..."
24,이주미 파자마 샤워가운 안경케이스 안경테 볼펜 도시락통 룸슬리퍼 세정티슈 트리트먼트...,https://blog.naver.com/hkh443/223751149610,2025-02-07 12:12:34+09:00,"이주미,이주미아이템,이주미파자마,이주미샤워가운,이주미안경케이스,이주미안경테,이주미볼..."
25,양세찬 유행템 쑥쑥 유행 희망템 아이템 정보,https://blog.naver.com/hkh443/223750560190,2025-02-07 02:01:34+09:00,"양세찬쑥쑥,쑥쑥아이템,양세찬유행템"
26,나솔사계 경리 아가일 반팔 니트 패션 99회,https://blog.naver.com/hkh443/223750501840,2025-02-07 00:53:13+09:00,"나솔사계,나솔사계패션,경리,경리패션,경리니트"
27,최화정 석쇠 투명지갑 향수 진주 목걸이 귀걸이 블러셔 아로마오일 가방 괄사 핸드크림...,https://blog.naver.com/hkh443/223750217199,2025-02-06 20:59:10+09:00,"최화정,최화정인생템,최화정석쇠,최화정투명지갑,최화정향수,최화정진주목걸이,최화정진주귀..."
28,나는솔로 송해나 가디건 데프콘 니트 이이경 체크 자켓 점퍼 패션 187회,https://blog.naver.com/hkh443/223749264610,2025-02-06 02:25:01+09:00,"나는솔로,나는솔로패션,송해나패션,송해나,송해나가디건,데프콘니트,이이경자켓"
29,라디오스타 장도연 오프숄더 니트 그레이 패션 900회,https://blog.naver.com/hkh443/223749253334,2025-02-06 02:02:03+09:00,"라디오스타,라디오스타패션,장도연패션,장도연니트,장도연오프숄더니트"
30,강주은 거울 앰플 마스크팩 패치 선크림 립펜슬 섀도우 아이라이너 컨실러 블러셔 브러...,https://blog.naver.com/hkh443/223749246000,2025-02-06 01:48:04+09:00,"강주은,강주은아이템,강주은거울,강주은크림,강주은앰플,강주은패치,강주은선크림,강주은컨..."
31,부승관 가방 프로틴 음료 손소독 물티슈 사탕 이클립스 괄사 세럼 선크림 왓츠인마이백...,https://blog.naver.com/hkh443/223748365487,2025-02-05 11:28:58+09:00,"부승관,부승관왓츠인마이백,부승관프로틴,부승관세럼,부승관선크림,부승관괄사,부승관사탕,..."
32,최화정 절구통 구찌 장갑 수동 착즙기 오일가글 유튜브 안녕하세요,https://blog.naver.com/hprbel1097/223750429455,2025-02-06 23:50:58+09:00,"최화정오일가글,최화정가글,최화정동국제약,최화정절구통,최화정착즙기,최화정수동착즙기,최..."
33,최화정 퍼퓸 향수 셀린느 핸드백 버킷백 가방 보석 파우치 머리핀 안경 선글라스 유튜...,https://blog.naver.com/hprbel1097/223750407473,2025-02-06 23:33:04+09:00,"최화정보석함,최화정보석파우치,최화정퍼퓸,최화정향수,최화정셀린느,최화정핸드백,최화정가..."
34,최화정 마사지기 루즈 보관용 투명지갑 목걸이 미니석쇠 앞치마 블러쉬 핸드크림 아로마...,https://blog.naver.com/hprbel1097/223750377422,2025-02-06 23:10:10+09:00,"최화정블러쉬,최화정목걸이,최화정반클리프,최화정설화수,최화정마사지기,최화정앞치마,최화..."
35,나는솔로 187회 송해나 옷 가디건 이이경 옷 체크 자켓 데프콘 옷 니트 스웨터 패...,https://blog.naver.com/hprbel1097/223750347077,2025-02-06 22:46:13+09:00,"나는솔로187회이이경옷,나는솔로187회이이경패션,나는솔로187회이이경코디,나는솔로1..."
36,나는솔로 187회 24기 옥순 숄더백 영자 핸드백 영숙 토트백 정숙 핸드백 가방 패...,https://blog.naver.com/hprbel1097/223750316665,2025-02-06 22:22:05+09:00,
37,환승연애 3회 혜선 루이비통 숄더백 가방 나언 샤넬백 가방 또 다른 시작 패션,https://blog.naver.com/hprbel1097/223749013083,2025-02-05 21:23:20+09:00,"환승연애또다른시작3회혜선가방,환승연애또다른시작3회혜선루이비통,환승연애또다른시작3회혜..."
38,환승연애 3회 이지연 옷 원피스 민소매 샤넬백 숄더백 가방 또 다른 시작 패션 코디 의상,https://blog.naver.com/hprbel1097/223749003503,2025-02-05 21:13:15+09:00,"환승연애또다른시작3회이지연옷,환승연애또다른시작3회이지연패션,환승연애또다른시작3회이지..."
39,환승연애 3회 박지연 옷 니트 오프숄더 레이스 원피스 후드티 또 다른 시작 패션 코...,https://blog.naver.com/hprbel1097/223748984529,2025-02-05 20:52:47+09:00,"환승연애또다른시작3회박지연옷,환승연애또다른시작3회박지연패션,환승연애또다른시작3회박지..."
40,라디오스타 900회 박나래 옷 도트 오프숄더 셔츠 블라우스 문세윤 옷 자켓 패션 코...,https://blog.naver.com/hprbel1097/223748965599,2025-02-05 20:32:46+09:00,"라디오스타900회문세윤옷,라디오스타900회문세윤패션,라디오스타900회문세윤코디,라디..."
41,라디오스타 900회 유세윤 옷 자켓 집업 가디건 장도연 옷 오프숄더 니트 코쿤 옷 ...,https://blog.naver.com/hprbel1097/223748955848,2025-02-05 20:22:11+09:00,"라디오스타900회장도연옷,라디오스타900회장도연패션,라디오스타900회장도연코디,라디..."
42,최화정 향수 퍼퓸 킬리안 바이레도 괄사 마사지기 설화수 진옥 백옥 마사지 아로마 오일,https://blog.naver.com/hsh6566/223751314968,2025-02-07 14:05:52+09:00,"최화정향수,최화정괄사,최화정아로마오일"
43,최화정 화로 가정용 미니 석쇠 구이 그릴 레몬 착즙기 레몬즙 짜개 스퀴저 즙짜개 접...,https://blog.naver.com/hsh6566/223750984544,2025-02-07 10:25:27+09:00,"최화정화로,최화정석쇠,최화정그릴,최화정레몬착즙기,최화정레몬즙짜개"
44,최화정 투명 지갑 비닐 파우치 동전 자라 버킷백 셀린느 가방 구찌 장갑 블러셔 앞머...,https://blog.naver.com/hsh6566/223750871127,2025-02-07 08:52:55+09:00,"최화정투명지갑,최화정버킷백,최화정구찌장갑,최화정블러셔,최화정찍찍이"
45,최화정 진주 목걸이 반클리프 터키석 터콰이즈 귀걸이 뿔테 안경 카린 선글라스 인생템,https://blog.naver.com/hsh6566/223750315721,2025-02-07 06:30:00+09:00,"최화정진주목걸이,최화정반클리프목걸이,최화정진주귀걸이,최화정안경,최화정선글라스"
46,나는솔로 송해나 하트 가디건 데프콘 니트 스웨터 이이경 체크 자켓 점퍼 잠바 187...,https://blog.naver.com/hsh6566/223749427609,2025-02-06 08:37:27+09:00,"송해나가디건,데프콘니트,이이경자켓"
47,강주은 헉슬리 화장품 MALU WILZ 컨실러 섀도우 아이라이너 크림 앰플 마스크팩...,https://blog.naver.com/hsh6566/223749015697,2025-02-06 06:30:00+09:00,"강주은화장품,강주은헉슬리,강주은컨실러,강주은섀도우,강주은앰플,강주은크림"
48,강주은 심플휴먼 거울 로마 헤어 에센스 브러쉬 빗 브러시 머리 드라이기 다이슨 드라...,https://blog.naver.com/hsh6566/223749015438,2025-02-06 04:30:00+09:00,"강주은거울,강주은에센스,강주은브러쉬,강주은빗,강주은드라이기"
49,솔로지옥 이시안 목걸이 루이비통 V 시안 셀린느 가방 9회 10회 정보,https://blog.naver.com/hsh6566/223749013033,2025-02-05 21:23:17+09:00,"이시안목걸이,이시안가방"
50,나래식 20회 아이브 가을 가디건 레드 패션 옷 브랜드 정보,https://blog.naver.com/pravas/223750795291,2025-02-07 07:31:54+09:00,"나래식,나래식아이브,아이브,아이브가을,아이브가을옷,가을,론론,론론가디건,나래식가을,..."
51,꼬꼬무 161회 장도연 아이키 옷 패션 블랙 검정 그레이 차콜 사이드 버튼 단추 니...,https://blog.naver.com/pravas/223750490487,2025-02-07 00:41:49+09:00,"꼬꼬무,꼬꼬무아이키,꼬꼬무장도연,아이키,장도연,장도연옷,장도연니트,꼬꼬무장도연니트,..."
52,나솔사계 99회 돌싱특집 경리 옷 패션 아가일 패턴 베이지 니트 스웨터 브랜드 정보...,https://blog.naver.com/pravas/223750463198,2025-02-07 00:17:26+09:00,"나솔사계,나솔사계경리,나솔사계경리옷,나솔사계경리니트,경리,경리옷,그로브,그로브니트,..."
53,나는솔로 187회 송해나 가디건 옷 하트그림 스티치 자수 아이보리 니트 패션 브랜드 정보,https://blog.naver.com/pravas/223750076106,2025-02-06 18:17:11+09:00,"나는솔로,나는솔로다,나는솔로다24기,나는솔로송해나,송해나,송해나옷,송해나가디건,데이..."
54,사장은 아무나 하나 4회 한혜진 옷 패션 옐로우 그라데이션 니트 가디건 노란 가디건...,https://blog.naver.com/pravas/223750048432,2025-02-06 17:51:10+09:00,"사장은아무나하나,사장은아무나하나한혜진,한혜진,한혜진가디건,한혜진옷,한혜진패션,스타패..."
55,라디오스타 900회 장도연 오프숄더 니트 스웨터 유세윤 가디건 자켓 옷 패션 코디 ...,https://blog.naver.com/pravas/223750031359,2025-02-06 17:36:49+09:00,"라디오스타,라디오스타900회,라디오스타장도연,장도연,장도연옷,오프숄더니트,인스턴트펑..."
56,최화정 미니석쇠 그릴 투명지갑 괄사 목걸이 귀걸이 가방 버킷백 핸드크림 아로마오일 ...,https://blog.naver.com/lzheng/223750201349,2025-02-06 20:40:40+09:00,"9101,최화정미니석쇠그릴,최화정투명지갑,최화정괄사,최화정목걸이,최화정귀걸이,최화정..."
57,강주은 화장품 크림 오일 앰플 패치 선크림 컨실러 아이섀도우 아이라이너 브러시 블러...,https://blog.naver.com/lzheng/223749738832,2025-02-06 13:30:41+09:00,"강주은화장품,강주은메이크업,강주은스킨케어,강주은거울,강주은크림,강주은오일,강주은앰플..."
58,강주은 메이크업 피부 헤어 아이템 정보 거울 시슬리 선크림앰플 선크림 컨실러 블러셔...,https://blog.naver.com/unknown0998/223751412430,2025-02-07 15:06:39+09:00,
59,신애라 애라원 테라피 에어프라이어 찜기 두유제조기 정보,https://blog.naver.com/unknown0998/223748573110,2025-02-05 14:38:02+09:00,"애라원,에어프라이어,두유제조기,멀티쿠커"

In [14]:
# date 1 days ago from now (date : dtype=datetime64[ns, UTC+09:00] usin np.datetime64
date_1d = pd.to_datetime('now', utc=True)
date_1d_ago = date_1d - pd.DateOffset(days=1)
date_1d_ago = date_1d_ago.floor('D')
df2 = df[df['date'] >= date_1d_ago]
df2.reset_index(drop=True, inplace=True)
df2.to_csv('blog_data/test2.csv')
df2

,title,url,date,tag
0,전참시 김아영 화병 홈앤하비 도자기화병 세라믹 인테리어 고리형,https://blog.naver.com/bcf5qp11/223750032612,2025-02-07 07:00:00+09:00,"전지적참견시점,김아영,홈앤하비,도자기화병,모던인테리어,홈데코,감성인테리어,꽃꽂이,세..."
1,전참시 김아영 다도세트 자사호 전통다기세트 찻잔세트 다도용품,https://blog.naver.com/bcf5qp11/223750015985,2025-02-06 19:00:00+09:00,"전지적참견시점,김아영,자사호다도세트,전통다도,차도구,보이차,우롱차,홍차,다도용품,찻..."
2,강주은 시슬리 화장품 나스 컨실러 쉐도우 팔레트 헉슬리 크림 세럼 거울,https://blog.naver.com/celubdigging/223751391830,2025-02-07 14:53:45+09:00,"강주은,메이크업템,뷰티추천,강주은화장품,50대뷰티,자연스러운메이크업,럭셔리스킨케어,..."
3,강주은 드라이기 돈모 롤빗 브러쉬,https://blog.naver.com/celubdigging/223750065876,2025-02-06 18:06:45+09:00,"강주은,강주은곱슬머리,강주은드라이기,강주은헤어드라이어,강주은롤빗,강주은돈모브러쉬,강..."
4,나솔사계 경리 반팔 니트 미니스커트 정보,https://blog.naver.com/celubdigging/223749999680,2025-02-06 17:09:33+09:00,"나솔사계,나솔사계99화,경리패션,경리아가일니트,경리스커트,그로브,아가일패턴,봄코디,..."
5,이주미 애장템 핸드폰 케이스 샤워가운 자주 파자마 도시락통 멀티스틱 곱창 4색볼펜 ...,https://blog.naver.com/celubdigging/223749797103,2025-02-06 14:21:07+09:00,"이주미,이주미애장템,이주미애장품,이주미핸드폰케이스,이주미신지모루,이주미안경,이주미케..."
6,시슬리 화장품만 쓰는 강주은이 추천하는 헉슬리,https://blog.naver.com/dehi61/223751438018,2025-02-07 15:22:02+09:00,"강주은,메이크업템,뷰티추천,강주은화장품,50대뷰티,자연스러운메이크업,럭셔리스킨케어,..."
7,강주은 charis 드라이기 2만원대 밖에 안하네요,https://blog.naver.com/dehi61/223750068994,2025-02-06 18:09:52+09:00,"강주은,강주은드라이기,가성비드라이기,강주은롤빗,돈모브러쉬,헤어관리,스타일링팁,볼륨드라이"
8,나솔사계 99화 경리 패션 찾았어요,https://blog.naver.com/dehi61/223750003834,2025-02-06 17:12:59+09:00,"나솔사계,나솔사계99화,경리패션,경리아가일니트,경리스커트,그로브,아가일패턴,봄코디,..."
9,이주미 자주 파자마 물티슈 파우치는 더 저렴한거 추천드림,https://blog.naver.com/dehi61/223749820907,2025-02-06 14:40:52+09:00,"이주미애장템,이주미추천템,이주미돈모브러쉬,이주미신지모루,이주미도시락,이주미파자마,이..."
10,유나 클렌저 괄사 향수 목마사지기 헤어브러쉬 빗 ITZY 있지 유난히빛이나 왓츠인마...,https://blog.naver.com/hkh443/223751349466,2025-02-07 14:27:29+09:00,"유나,있지유나,유나아이템,유나클렌저,유나향수,유나괄사,유나목마사지기,유나헤어브러쉬,유나빗"
11,이현이 샤워필터 연수기 욕실정리 한강라면기계 제조기 아이템 정보,https://blog.naver.com/hkh443/223751263683,2025-02-07 13:31:00+09:00,"이현이,이현이아이템,이현이샤워필터,이현이연수기,이현이한강라면,이현이라면기계,이현이라..."
12,애라원 신애라 잡곡 쌀통 밥솥 찜기 두유제조기 에어프라이어 솔잎 추출물 건강식품 주...,https://blog.naver.com/hkh443/223751217913,2025-02-07 13:00:41+09:00,"애라원,애라원주방용품,신애라,신애라주방용품,애라원쌀통,애라원밥솥,애라원찜기,애라원두..."
13,이주미 파자마 샤워가운 안경케이스 안경테 볼펜 도시락통 룸슬리퍼 세정티슈 트리트먼트...,https://blog.naver.com/hkh443/223751149610,2025-02-07 12:12:34+09:00,"이주미,이주미아이템,이주미파자마,이주미샤워가운,이주미안경케이스,이주미안경테,이주미볼..."
14,양세찬 유행템 쑥쑥 유행 희망템 아이템 정보,https://blog.naver.com/hkh443/223750560190,2025-02-07 02:01:34+09:00,"양세찬쑥쑥,쑥쑥아이템,양세찬유행템"
15,나솔사계 경리 아가일 반팔 니트 패션 99회,https://blog.naver.com/hkh443/223750501840,2025-02-07 00:53:13+09:00,"나솔사계,나솔사계패션,경리,경리패션,경리니트"
16,최화정 석쇠 투명지갑 향수 진주 목걸이 귀걸이 블러셔 아로마오일 가방 괄사 핸드크림...,https://blog.naver.com/hkh443/223750217199,2025-02-06 20:59:10+09:00,"최화정,최화정인생템,최화정석쇠,최화정투명지갑,최화정향수,최화정진주목걸이,최화정진주귀..."
17,최화정 절구통 구찌 장갑 수동 착즙기 오일가글 유튜브 안녕하세요,https://blog.naver.com/hprbel1097/223750429455,2025-02-06 23:50:58+09:00,"최화정오일가글,최화정가글,최화정동국제약,최화정절구통,최화정착즙기,최화정수동착즙기,최..."
18,최화정 퍼퓸 향수 셀린느 핸드백 버킷백 가방 보석 파우치 머리핀 안경 선글라스 유튜...,https://blog.naver.com/hprbel1097/223750407473,2025-02-06 23:33:04+09:00,"최화정보석함,최화정보석파우치,최화정퍼퓸,최화정향수,최화정셀린느,최화정핸드백,최화정가..."
19,최화정 마사지기 루즈 보관용 투명지갑 목걸이 미니석쇠 앞치마 블러쉬 핸드크림 아로마...,https://blog.naver.com/hprbel1097/223750377422,2025-02-06 23:10:10+09:00,"최화정블러쉬,최화정목걸이,최화정반클리프,최화정설화수,최화정마사지기,최화정앞치마,최화..."
20,나는솔로 187회 송해나 옷 가디건 이이경 옷 체크 자켓 데프콘 옷 니트 스웨터 패...,https://blog.naver.com/hprbel1097/223750347077,2025-02-06 22:46:13+09:00,"나는솔로187회이이경옷,나는솔로187회이이경패션,나는솔로187회이이경코디,나는솔로1..."
21,나는솔로 187회 24기 옥순 숄더백 영자 핸드백 영숙 토트백 정숙 핸드백 가방 패...,https://blog.naver.com/hprbel1097/223750316665,2025-02-06 22:22:05+09:00,
22,최화정 향수 퍼퓸 킬리안 바이레도 괄사 마사지기 설화수 진옥 백옥 마사지 아로마 오일,https://blog.naver.com/hsh6566/223751314968,2025-02-07 14:05:52+09:00,"최화정향수,최화정괄사,최화정아로마오일"
23,최화정 화로 가정용 미니 석쇠 구이 그릴 레몬 착즙기 레몬즙 짜개 스퀴저 즙짜개 접...,https://blog.naver.com/hsh6566/223750984544,2025-02-07 10:25:27+09:00,"최화정화로,최화정석쇠,최화정그릴,최화정레몬착즙기,최화정레몬즙짜개"
24,최화정 투명 지갑 비닐 파우치 동전 자라 버킷백 셀린느 가방 구찌 장갑 블러셔 앞머...,https://blog.naver.com/hsh6566/223750871127,2025-02-07 08:52:55+09:00,"최화정투명지갑,최화정버킷백,최화정구찌장갑,최화정블러셔,최화정찍찍이"
25,최화정 진주 목걸이 반클리프 터키석 터콰이즈 귀걸이 뿔테 안경 카린 선글라스 인생템,https://blog.naver.com/hsh6566/223750315721,2025-02-07 06:30:00+09:00,"최화정진주목걸이,최화정반클리프목걸이,최화정진주귀걸이,최화정안경,최화정선글라스"
26,나래식 20회 아이브 가을 가디건 레드 패션 옷 브랜드 정보,https://blog.naver.com/pravas/223750795291,2025-02-07 07:31:54+09:00,"나래식,나래식아이브,아이브,아이브가을,아이브가을옷,가을,론론,론론가디건,나래식가을,..."
27,꼬꼬무 161회 장도연 아이키 옷 패션 블랙 검정 그레이 차콜 사이드 버튼 단추 니...,https://blog.naver.com/pravas/223750490487,2025-02-07 00:41:49+09:00,"꼬꼬무,꼬꼬무아이키,꼬꼬무장도연,아이키,장도연,장도연옷,장도연니트,꼬꼬무장도연니트,..."
28,나솔사계 99회 돌싱특집 경리 옷 패션 아가일 패턴 베이지 니트 스웨터 브랜드 정보...,https://blog.naver.com/pravas/223750463198,2025-02-07 00:17:26+09:00,"나솔사계,나솔사계경리,나솔사계경리옷,나솔사계경리니트,경리,경리옷,그로브,그로브니트,..."
29,나는솔로 187회 송해나 가디건 옷 하트그림 스티치 자수 아이보리 니트 패션 브랜드 정보,https://blog.naver.com/pravas/223750076106,2025-02-06 18:17:11+09:00,"나는솔로,나는솔로다,나는솔로다24기,나는솔로송해나,송해나,송해나옷,송해나가디건,데이..."
30,사장은 아무나 하나 4회 한혜진 옷 패션 옐로우 그라데이션 니트 가디건 노란 가디건...,https://blog.naver.com/pravas/223750048432,2025-02-06 17:51:10+09:00,"사장은아무나하나,사장은아무나하나한혜진,한혜진,한혜진가디건,한혜진옷,한혜진패션,스타패..."
31,라디오스타 900회 장도연 오프숄더 니트 스웨터 유세윤 가디건 자켓 옷 패션 코디 ...,https://blog.naver.com/pravas/223750031359,2025-02-06 17:36:49+09:00,"라디오스타,라디오스타900회,라디오스타장도연,장도연,장도연옷,오프숄더니트,인스턴트펑..."
32,최화정 미니석쇠 그릴 투명지갑 괄사 목걸이 귀걸이 가방 버킷백 핸드크림 아로마오일 ...,https://blog.naver.com/lzheng/223750201349,2025-02-06 20:40:40+09:00,"9101,최화정미니석쇠그릴,최화정투명지갑,최화정괄사,최화정목걸이,최화정귀걸이,최화정..."
33,강주은 화장품 크림 오일 앰플 패치 선크림 컨실러 아이섀도우 아이라이너 브러시 블러...,https://blog.naver.com/lzheng/223749738832,2025-02-06 13:30:41+09:00,"강주은화장품,강주은메이크업,강주은스킨케어,강주은거울,강주은크림,강주은오일,강주은앰플..."
34,강주은 메이크업 피부 헤어 아이템 정보 거울 시슬리 선크림앰플 선크림 컨실러 블러셔...,https://blog.naver.com/unknown0998/223751412430,2025-02-07 15:06:39+09:00,

In [ ]:
from openai import OpenAI

api_key = ""
client = OpenAI(api_key=api_key)


def extract_celeb(title):
    print(title)
    response = client.chat.completions.create(
        model="gpt-4o-mini-2024-07-18",
        messages=[
            {
                "role": "system",
                "content": [
                    {
                        "type": "text",
                        "text": "문구를 입력하면 그 문구로부터 연예인의 이름을 찾아서 출력해줘. 문장이 나와도 문장에 대답하지 말고, 해당 문장에 등장하는 연예인의 이름만 찾아서 출력해.",
                    }
                ],
            },
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": "한지민 올리브데올리브 언발란스 니트 셋업 풀오버 나완비 코디",
                    }
                ],
            },
            {"role": "assistant", "content": [{"type": "text", "text": "한지민"}]},
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": "독수리5형제를부탁해 1회 엄지원 옷 니트 스웨터 가디건 폴로 숄더백 가방 시계 마광숙 패션 코디 의상",
                    }
                ],
            },
            {
                "role": "assistant",
                "content": [{"type": "text", "text": "엄지원, 마광숙"}],
            },
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": "김대호 나혼자산다 하차 선물 가격은?",
                    }
                ],
            },
            {
                "role": "assistant",
                "content": [{"type": "text", "text": "김대호"}],
            },
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": title,
                    }
                ],
            },
        ],
        response_format={"type": "text"},
        temperature=1,
        max_completion_tokens=10000,
        top_p=1,
        frequency_penalty=0,
        presence_penalty=0,
    )
    ans = response.choices[0].message.content.strip()
    print(ans)
    return ans

In [16]:
resp = extract_celeb('나혼자산다 김대호 집 사우나 기계 건습식 맥반석 건식 습식 핀란드 사우나기 나혼산 대호 아나운서 찜질방')
resp

나혼자산다 김대호 집 사우나 기계 건습식 맥반석 건식 습식 핀란드 사우나기 나혼산 대호 아나운서 찜질방
김대호

'김대호'

In [17]:
df2['celeb'] = df2['title'].apply(extract_celeb)
df2.to_csv('blog_data/test3.csv')
df2

전참시 김아영 화병 홈앤하비 도자기화병 세라믹 인테리어 고리형
김아영
전참시 김아영 다도세트 자사호 전통다기세트 찻잔세트 다도용품
김아영
강주은 시슬리 화장품 나스 컨실러 쉐도우 팔레트 헉슬리 크림 세럼 거울

KeyboardInterrupt:

In [1]:
import pandas as pd
df2 = pd.read_csv('blog_data/test3.csv', index_col=0)
df2

,title,url,date,tag,celeb
0,전참시 김아영 화병 홈앤하비 도자기화병 세라믹 인테리어 고리형,https://blog.naver.com/bcf5qp11/223750032612,2025-02-07 07:00:00+09:00,"전지적참견시점,김아영,홈앤하비,도자기화병,모던인테리어,홈데코,감성인테리어,꽃꽂이,세...",김아영
1,전참시 김아영 다도세트 자사호 전통다기세트 찻잔세트 다도용품,https://blog.naver.com/bcf5qp11/223750015985,2025-02-06 19:00:00+09:00,"전지적참견시점,김아영,자사호다도세트,전통다도,차도구,보이차,우롱차,홍차,다도용품,찻...",김아영
2,강주은 시슬리 화장품 나스 컨실러 쉐도우 팔레트 헉슬리 크림 세럼 거울,https://blog.naver.com/celubdigging/223751391830,2025-02-07 14:53:45+09:00,"강주은,메이크업템,뷰티추천,강주은화장품,50대뷰티,자연스러운메이크업,럭셔리스킨케어,...",강주은
3,강주은 드라이기 돈모 롤빗 브러쉬,https://blog.naver.com/celubdigging/223750065876,2025-02-06 18:06:45+09:00,"강주은,강주은곱슬머리,강주은드라이기,강주은헤어드라이어,강주은롤빗,강주은돈모브러쉬,강...",강주은
4,나솔사계 경리 반팔 니트 미니스커트 정보,https://blog.naver.com/celubdigging/223749999680,2025-02-06 17:09:33+09:00,"나솔사계,나솔사계99화,경리패션,경리아가일니트,경리스커트,그로브,아가일패턴,봄코디,...",경리
5,이주미 애장템 핸드폰 케이스 샤워가운 자주 파자마 도시락통 멀티스틱 곱창 4색볼펜 ...,https://blog.naver.com/celubdigging/223749797103,2025-02-06 14:21:07+09:00,"이주미,이주미애장템,이주미애장품,이주미핸드폰케이스,이주미신지모루,이주미안경,이주미케...",이주미
6,시슬리 화장품만 쓰는 강주은이 추천하는 헉슬리,https://blog.naver.com/dehi61/223751438018,2025-02-07 15:22:02+09:00,"강주은,메이크업템,뷰티추천,강주은화장품,50대뷰티,자연스러운메이크업,럭셔리스킨케어,...",강주은
7,강주은 charis 드라이기 2만원대 밖에 안하네요,https://blog.naver.com/dehi61/223750068994,2025-02-06 18:09:52+09:00,"강주은,강주은드라이기,가성비드라이기,강주은롤빗,돈모브러쉬,헤어관리,스타일링팁,볼륨드라이",강주은
8,나솔사계 99화 경리 패션 찾았어요,https://blog.naver.com/dehi61/223750003834,2025-02-06 17:12:59+09:00,"나솔사계,나솔사계99화,경리패션,경리아가일니트,경리스커트,그로브,아가일패턴,봄코디,...",경리
9,이주미 자주 파자마 물티슈 파우치는 더 저렴한거 추천드림,https://blog.naver.com/dehi61/223749820907,2025-02-06 14:40:52+09:00,"이주미애장템,이주미추천템,이주미돈모브러쉬,이주미신지모루,이주미도시락,이주미파자마,이...",이주미
10,유나 클렌저 괄사 향수 목마사지기 헤어브러쉬 빗 ITZY 있지 유난히빛이나 왓츠인마...,https://blog.naver.com/hkh443/223751349466,2025-02-07 14:27:29+09:00,"유나,있지유나,유나아이템,유나클렌저,유나향수,유나괄사,유나목마사지기,유나헤어브러쉬,유나빗","유나, ITZY"
11,이현이 샤워필터 연수기 욕실정리 한강라면기계 제조기 아이템 정보,https://blog.naver.com/hkh443/223751263683,2025-02-07 13:31:00+09:00,"이현이,이현이아이템,이현이샤워필터,이현이연수기,이현이한강라면,이현이라면기계,이현이라...",이현이
12,애라원 신애라 잡곡 쌀통 밥솥 찜기 두유제조기 에어프라이어 솔잎 추출물 건강식품 주...,https://blog.naver.com/hkh443/223751217913,2025-02-07 13:00:41+09:00,"애라원,애라원주방용품,신애라,신애라주방용품,애라원쌀통,애라원밥솥,애라원찜기,애라원두...",신애라
13,이주미 파자마 샤워가운 안경케이스 안경테 볼펜 도시락통 룸슬리퍼 세정티슈 트리트먼트...,https://blog.naver.com/hkh443/223751149610,2025-02-07 12:12:34+09:00,"이주미,이주미아이템,이주미파자마,이주미샤워가운,이주미안경케이스,이주미안경테,이주미볼...",이주미
14,양세찬 유행템 쑥쑥 유행 희망템 아이템 정보,https://blog.naver.com/hkh443/223750560190,2025-02-07 02:01:34+09:00,"양세찬쑥쑥,쑥쑥아이템,양세찬유행템",양세찬
15,나솔사계 경리 아가일 반팔 니트 패션 99회,https://blog.naver.com/hkh443/223750501840,2025-02-07 00:53:13+09:00,"나솔사계,나솔사계패션,경리,경리패션,경리니트",경리
16,최화정 석쇠 투명지갑 향수 진주 목걸이 귀걸이 블러셔 아로마오일 가방 괄사 핸드크림...,https://blog.naver.com/hkh443/223750217199,2025-02-06 20:59:10+09:00,"최화정,최화정인생템,최화정석쇠,최화정투명지갑,최화정향수,최화정진주목걸이,최화정진주귀...",최화정
17,최화정 절구통 구찌 장갑 수동 착즙기 오일가글 유튜브 안녕하세요,https://blog.naver.com/hprbel1097/223750429455,2025-02-06 23:50:58+09:00,"최화정오일가글,최화정가글,최화정동국제약,최화정절구통,최화정착즙기,최화정수동착즙기,최...",최화정
18,최화정 퍼퓸 향수 셀린느 핸드백 버킷백 가방 보석 파우치 머리핀 안경 선글라스 유튜...,https://blog.naver.com/hprbel1097/223750407473,2025-02-06 23:33:04+09:00,"최화정보석함,최화정보석파우치,최화정퍼퓸,최화정향수,최화정셀린느,최화정핸드백,최화정가...",최화정
19,최화정 마사지기 루즈 보관용 투명지갑 목걸이 미니석쇠 앞치마 블러쉬 핸드크림 아로마...,https://blog.naver.com/hprbel1097/223750377422,2025-02-06 23:10:10+09:00,"최화정블러쉬,최화정목걸이,최화정반클리프,최화정설화수,최화정마사지기,최화정앞치마,최화...",최화정
20,나는솔로 187회 송해나 옷 가디건 이이경 옷 체크 자켓 데프콘 옷 니트 스웨터 패...,https://blog.naver.com/hprbel1097/223750347077,2025-02-06 22:46:13+09:00,"나는솔로187회이이경옷,나는솔로187회이이경패션,나는솔로187회이이경코디,나는솔로1...","송해나, 이이경, 데프콘"
21,나는솔로 187회 24기 옥순 숄더백 영자 핸드백 영숙 토트백 정숙 핸드백 가방 패...,https://blog.naver.com/hprbel1097/223750316665,2025-02-06 22:22:05+09:00,NaN,"옥순, 영자, 영숙, 정숙"
22,최화정 향수 퍼퓸 킬리안 바이레도 괄사 마사지기 설화수 진옥 백옥 마사지 아로마 오일,https://blog.naver.com/hsh6566/223751314968,2025-02-07 14:05:52+09:00,"최화정향수,최화정괄사,최화정아로마오일",최화정
23,최화정 화로 가정용 미니 석쇠 구이 그릴 레몬 착즙기 레몬즙 짜개 스퀴저 즙짜개 접...,https://blog.naver.com/hsh6566/223750984544,2025-02-07 10:25:27+09:00,"최화정화로,최화정석쇠,최화정그릴,최화정레몬착즙기,최화정레몬즙짜개",최화정
24,최화정 투명 지갑 비닐 파우치 동전 자라 버킷백 셀린느 가방 구찌 장갑 블러셔 앞머...,https://blog.naver.com/hsh6566/223750871127,2025-02-07 08:52:55+09:00,"최화정투명지갑,최화정버킷백,최화정구찌장갑,최화정블러셔,최화정찍찍이",최화정
25,최화정 진주 목걸이 반클리프 터키석 터콰이즈 귀걸이 뿔테 안경 카린 선글라스 인생템,https://blog.naver.com/hsh6566/223750315721,2025-02-07 06:30:00+09:00,"최화정진주목걸이,최화정반클리프목걸이,최화정진주귀걸이,최화정안경,최화정선글라스",최화정
26,나래식 20회 아이브 가을 가디건 레드 패션 옷 브랜드 정보,https://blog.naver.com/pravas/223750795291,2025-02-07 07:31:54+09:00,"나래식,나래식아이브,아이브,아이브가을,아이브가을옷,가을,론론,론론가디건,나래식가을,...",아이브
27,꼬꼬무 161회 장도연 아이키 옷 패션 블랙 검정 그레이 차콜 사이드 버튼 단추 니...,https://blog.naver.com/pravas/223750490487,2025-02-07 00:41:49+09:00,"꼬꼬무,꼬꼬무아이키,꼬꼬무장도연,아이키,장도연,장도연옷,장도연니트,꼬꼬무장도연니트,...","장도연, 아이키"
28,나솔사계 99회 돌싱특집 경리 옷 패션 아가일 패턴 베이지 니트 스웨터 브랜드 정보...,https://blog.naver.com/pravas/223750463198,2025-02-07 00:17:26+09:00,"나솔사계,나솔사계경리,나솔사계경리옷,나솔사계경리니트,경리,경리옷,그로브,그로브니트,...",경리
29,나는솔로 187회 송해나 가디건 옷 하트그림 스티치 자수 아이보리 니트 패션 브랜드 정보,https://blog.naver.com/pravas/223750076106,2025-02-06 18:17:11+09:00,"나는솔로,나는솔로다,나는솔로다24기,나는솔로송해나,송해나,송해나옷,송해나가디건,데이...",송해나
30,사장은 아무나 하나 4회 한혜진 옷 패션 옐로우 그라데이션 니트 가디건 노란 가디건...,https://blog.naver.com/pravas/223750048432,2025-02-06 17:51:10+09:00,"사장은아무나하나,사장은아무나하나한혜진,한혜진,한혜진가디건,한혜진옷,한혜진패션,스타패...",한혜진
31,라디오스타 900회 장도연 오프숄더 니트 스웨터 유세윤 가디건 자켓 옷 패션 코디 ...,https://blog.naver.com/pravas/223750031359,2025-02-06 17:36:49+09:00,"라디오스타,라디오스타900회,라디오스타장도연,장도연,장도연옷,오프숄더니트,인스턴트펑...","장도연, 유세윤"
32,최화정 미니석쇠 그릴 투명지갑 괄사 목걸이 귀걸이 가방 버킷백 핸드크림 아로마오일 ...,https://blog.naver.com/lzheng/223750201349,2025-02-06 20:40:40+09:00,"9101,최화정미니석쇠그릴,최화정투명지갑,최화정괄사,최화정목걸이,최화정귀걸이,최화정...",최화정
33,강주은 화장품 크림 오일 앰플 패치 선크림 컨실러 아이섀도우 아이라이너 브러시 블러...,https://blog.naver.com/lzheng/223749738832,2025-02-06 13:30:41+09:00,"강주은화장품,강주은메이크업,강주은스킨케어,강주은거울,강주은크림,강주은오일,강주은앰플...",강주은
34,강주은 메이크업 피부 헤어 아이템 정보 거울 시슬리 선크림앰플 선크림 컨실러 블러셔...,https://blog.naver.com/unknown0998/223751412430,2025-02-07 15:06:39+09:00,NaN,강주은

In [3]:
celebs = []
for i in df2['celeb'].to_list():
    celebs += i.split(', ')
k = pd.DataFrame(celebs).value_counts()
k

0
최화정     9
강주은     6
경리      4
이주미     3
송해나     2
김아영     2
장도연     2
ITZY    1
데프콘     1
신애라     1
영숙      1
아이브     1
아이키     1
양세찬     1
유나      1
옥순      1
영자      1
유세윤     1
이현이     1
이이경     1
정숙      1
한혜진     1
Name: count, dtype: int64

In [4]:
tk = [x[0] for x in k.keys()][:3]
tk

['최화정', '강주은', '경리']

In [5]:
keyword = tk[0]

In [6]:
dft = df2[df2['title'].str.contains(keyword)].reset_index(drop=True)
dft

,title,url,date,tag,celeb
0,최화정 석쇠 투명지갑 향수 진주 목걸이 귀걸이 블러셔 아로마오일 가방 괄사 핸드크림...,https://blog.naver.com/hkh443/223750217199,2025-02-06 20:59:10+09:00,"최화정,최화정인생템,최화정석쇠,최화정투명지갑,최화정향수,최화정진주목걸이,최화정진주귀...",최화정
1,최화정 절구통 구찌 장갑 수동 착즙기 오일가글 유튜브 안녕하세요,https://blog.naver.com/hprbel1097/223750429455,2025-02-06 23:50:58+09:00,"최화정오일가글,최화정가글,최화정동국제약,최화정절구통,최화정착즙기,최화정수동착즙기,최...",최화정
2,최화정 퍼퓸 향수 셀린느 핸드백 버킷백 가방 보석 파우치 머리핀 안경 선글라스 유튜...,https://blog.naver.com/hprbel1097/223750407473,2025-02-06 23:33:04+09:00,"최화정보석함,최화정보석파우치,최화정퍼퓸,최화정향수,최화정셀린느,최화정핸드백,최화정가...",최화정
3,최화정 마사지기 루즈 보관용 투명지갑 목걸이 미니석쇠 앞치마 블러쉬 핸드크림 아로마...,https://blog.naver.com/hprbel1097/223750377422,2025-02-06 23:10:10+09:00,"최화정블러쉬,최화정목걸이,최화정반클리프,최화정설화수,최화정마사지기,최화정앞치마,최화...",최화정
4,최화정 향수 퍼퓸 킬리안 바이레도 괄사 마사지기 설화수 진옥 백옥 마사지 아로마 오일,https://blog.naver.com/hsh6566/223751314968,2025-02-07 14:05:52+09:00,"최화정향수,최화정괄사,최화정아로마오일",최화정
5,최화정 화로 가정용 미니 석쇠 구이 그릴 레몬 착즙기 레몬즙 짜개 스퀴저 즙짜개 접...,https://blog.naver.com/hsh6566/223750984544,2025-02-07 10:25:27+09:00,"최화정화로,최화정석쇠,최화정그릴,최화정레몬착즙기,최화정레몬즙짜개",최화정
6,최화정 투명 지갑 비닐 파우치 동전 자라 버킷백 셀린느 가방 구찌 장갑 블러셔 앞머...,https://blog.naver.com/hsh6566/223750871127,2025-02-07 08:52:55+09:00,"최화정투명지갑,최화정버킷백,최화정구찌장갑,최화정블러셔,최화정찍찍이",최화정
7,최화정 진주 목걸이 반클리프 터키석 터콰이즈 귀걸이 뿔테 안경 카린 선글라스 인생템,https://blog.naver.com/hsh6566/223750315721,2025-02-07 06:30:00+09:00,"최화정진주목걸이,최화정반클리프목걸이,최화정진주귀걸이,최화정안경,최화정선글라스",최화정
8,최화정 미니석쇠 그릴 투명지갑 괄사 목걸이 귀걸이 가방 버킷백 핸드크림 아로마오일 ...,https://blog.naver.com/lzheng/223750201349,2025-02-06 20:40:40+09:00,"9101,최화정미니석쇠그릴,최화정투명지갑,최화정괄사,최화정목걸이,최화정귀걸이,최화정...",최화정

In [7]:
keywords = []
for i in dft.title:
    for j in i.split(' '):
        keywords.append(j)
k = pd.DataFrame(keywords).value_counts()
k

0
최화정    9
목걸이    4
향수     4
가방     4
괄사     3
      ..
킬리안    1
카린     1
하트     1
핸드백    1
화로     1
Name: count, Length: 73, dtype: int64

In [45]:
import time, random
from fake_useragent import UserAgent

def crawling_waiting_time() -> None:
    return time.sleep(random.randint(1, 3))

def get_html(url):
    import requests

    # pretend headers
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
        "Accept-Language": "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7",
        "Referer": "https://blog.naver.com/",
        "Connection": "keep-alive",
        "Cache-Control": "max-age=0",
        "Upgrade-Insecure-Requests": "1",
    }
    response = requests.get(url, headers=headers, timeout=10)
    rurl = 'https://blog.naver.com/' + response.text.split('src="')[2].split('"\n')[0]
    print(rurl)
    response = requests.get(rurl, headers=headers, timeout=10)
    return response.text

In [14]:
def get_content(html):
    from bs4 import BeautifulSoup
    soup = BeautifulSoup(html.text, 'html.parser')
    output = '\n'.join([x.get_text() for x in soup.find_all("p", {"class":"se-text-paragraph"})])
    return output.replace('\u200b', '')

In [57]:
html = get_html('https://blog.naver.com/hkh443/223750217199	')
html

https://blog.naver.com//PostView.naver?blogId=hkh443&logNo=223750217199&redirect=Dlog&widgetTypeCall=true&topReferer=https%3A%2F%2Fblog.naver.com%2F&trackingCode=blog_etc&directAccess=false

'\r\n\r\n\r\n\r\n\r\n<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\r\n<html lang="ko">\r\n<head>\r\n<meta http-equiv="Pragma" content="no-cache" />\r\n<meta http-equiv="Expires" content="-1" />\r\n\r\n<meta name="referrer" content="always" />\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n<!--[if ie]>\r\n<style type="text/css">\r\nhtml {overflow: scroll; overflow-x: auto;}\r\n</style>\r\n<![endif]-->\r\n\r\n<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/t.static.blog/mylog/versioning/LayoutTopCommon-233548907_https.css" charset="UTF-8" />\r\n<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/t.static.blog/mylog/versioning//common/css/music/player-d3fc09e_https.css">\r\n\r\n<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?3" />\r\n\n\n\n\n\n \n\n\t\n\t\t<meta property="og:title" content="최화정 석쇠 투명지갑 향수 진주 목걸이 귀걸이 블러셔 아로마오일 가방 괄사 핸드크림 하트 앞머리 찍찍이 선글라스 인생템"/>\n\n\t\t\n\t\t\t\n\t\t\t\n\t\t\t<meta property="og:image" content="https://blogthumb.pstatic.net/MjAyNTAyMDZfNTYg/MDAxNzM4ODQyOTMxMTc0.x1yEgbjq3BjRjP8Zm_k0Va2FJSuJQQP_g4ROv7nnx8gg.z3NUMLhtKeSVD3ZNBKcCifB8Jp0gX2iXd9PSL9ujELQg.PNG/%C1%A6%B8%F1%C0%BB_%C0%D4%B7%C2%C7%D8%C1%D6%BC%BC%BF%E4_-001_%283%29.png?type=w2"/>\n\t\t\t\n\t\t\n        <meta property="og:description" content="프로그램명 (회차) 안녕하세요 최화정이에요 방송일정 : 2025.02.06 24년에 주구장창 마르고 닳다록 사용하..."/>\n\n\t\t\n\t\t\t<meta property="og:url" content="https://blog.naver.com/hkh443/223750217199"/>\n\t\t\n\t\n\t\n\n<meta property="me:feed:serviceId" content="blog" />\r\n<style type="text/css">\r\n/*<![CDATA[*/\r\n\n\nbody {background-color:rgb(255, 255, 255);background-image:url(https://ssl.pstatic.net/static/blog/skin/100/body.png);}\n#head-skin {background-image:url(https://ssl.pstatic.net/static/blog/skin/100/head-skin.png);}\n\n\n#whole-border {border-width:0px;border-color:rgb(0, 0, 0);border-style:solid;background:transparent;}\n#whole-head {height:0;background:transparent;}\n#whole-body {padding:0 8px;background:transparent;}\n#whole-footer {height:0;background:transparent;}\n\n\n#wrapper .side-border {border-width:0px;border-style:solid;border-color:rgb(0, 0, 0);border:0;}\n#wrapper .side-head {height:8px;background:transparent;}\n#wrapper .side-body {padding:0;background:transparent;}\n#wrapper .side-footer {height:8px;background:transparent;}\n\n\n#wrapper .cm-col1 {color:rgb(85, 85, 85);}\n#wrapper .cm-arw {background:rgb(85, 85, 85);}\n#wrapper div.line {border-top-color:rgb(85, 85, 85);}\n#wrapper .cm-border {border-width:0;border-style:solid;border-color:rgb(0, 0, 0);}\n#wrapper .cm-head {height:30px;background:none;}\n#wrapper .cm-body {background:transparent;}\n#wrapper .cm-footer {height:30px;background:url(https://ssl.pstatic.net/static/blog/skin/100/cm-footer.png);}\n#wrapper .cm-icol {color:rgb(85, 85, 85);}\n#wrapper h3 {margin-left:14px;bottom:7px;}\n#wrapper .cmore {bottom:7px;}\n#blog-category .listimage {background-image:url(https://blogimgs.pstatic.net/nblog/skins/infobox/0002_arw.gif);}\n#wrapper .buddyup {background-image:url(https://blogimgs.pstatic.net/nblog/skins/infobox/0002_icon_up.gif);}\n#wrapper .buddydw {background-image:url(https://blogimgs.pstatic.net/nblog/skins/infobox/0002_icon_down.gif);}\n#blog-category .f_icoclosed {background-image:url(https://blogimgs.pstatic.net/nblog/skins/infobox/ico_f_closed_l.gif) !important;}\n#blog-category .f_icoopen {background-image:url(https://blogimgs.pstatic.net/nblog/skins/infobox/ico_f_open_l.gif) !important;}\n#blog-category ul li.depth2 {background-image:url(https://blogimgs.pstatic.net/nblog/skins/infobox/ico_depth2_l.gif) !important;}\n\n* html #wrapper .cm-footer { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://ssl.pstatic.net/static/blog/skin/100/cm-footer.png,sizingMethod=crop); }\n\n#blog-gnb .link {color:#FFFFFF;}\n#blog-gnb .gnb_name {color:#FFFFFF;}\n#blog-gnb .bar {background:#FFFFFF;}\n#blog-gnb .btn_blog_login {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_login.png) no-repeat 0 0;}\n#blog-gnb .gnb_icon {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_menu.png) no-repeat 0 0 !important;}\n#blog-gnb .go-down {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_down.png);}\n#blog-gnb .gnb_my_namebox {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_down.png) no-repeat 100% 50% !important;}\n#blog-gnb .go-up {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_up.png);}\n#blog-gnb .gnb_lyr_opened .gnb_my_namebox {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_up.png) no-repeat 100% 50% !important;}\n\n* html #blog-gnb .btn_blog_login { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_login.png,sizingMethod=crop); }\n* html #blog-gnb .gnb_icon { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_menu.png,sizingMethod=crop); }\n* html #blog-gnb .go-down { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_down.png,sizingMethod=crop); }\n* html #blog-gnb .gnb_my_namebox { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_down.png,sizingMethod=crop); }\n* html #blog-gnb .go-up { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_up.png,sizingMethod=crop); }\n* html #blog-gnb .gnb_lyr_opened .gnb_my_namebox { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_up.png,sizingMethod=crop); }\n\n#foldset .go-left {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_left.png)}\n#foldset .go-right {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_right.png)}\n\n* html #foldset .go-left { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_left.png,sizingMethod=crop); }\n* html #foldset .go-right { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_right.png,sizingMethod=crop); }\n\n#body {width:982px; margin:0 auto; padding:0;}\r\nbody, #head-skin, #bottom-skin {background-position:50% 0;}\r\n#wrapper {width:966px;}\r\n#twocols {width:773px; display:inline; float:left;}\r\n#content-area {width:773px; display:inline; float:left;}\r\n#right-area {float:right;}\r\n.side-width-1 {width:185px;  display:inline;}\n\n\n\n.itemfont, a.itemfont:link, a.itemfont:visited, a.itemfont:hover, a.itemfont:active {font-size:9pt;font-family:돋움, 굴림, seoul, verdana, arial;}\na.itemTagfont:link, a.itemTagfont:visited {font-size:9pt;font-family:돋움, 굴림, seoul, verdana, arial;}\na.itemTagfont:hover , a.itemTagfont:active {font-size:9pt;font-family:돋움, 굴림, seoul, verdana, arial; color:#418F21;}\n.itemSubjectfont   {font-size:9pt;font-family:돋움, 굴림, seoul, verdana, arial;}\n#post-area .post_adpost .itemSubjectfont {font-size:10pt !important;font-family:돋움, 굴림, seoul, verdana, arial;}\n\n\n#blog-title {height:128px;background:transparent;}\n\n#blogTitleText {vertical-align:middle;text-align:left;}\n\n#blogTitleName {display:none;color:rgb(255, 255, 255);font-family:"바른고딕", NanumBarunGothic, NanumBarunGothicWebFont, "NanumBarun Gothic", "맑은 고딕", Dotum, "돋움", Helvetica, "Apple SD Gothic Neo", sans-serif;font-size:25px;}\n#blog-menu .border {height:38px;border-width:0px;border-color:rgb(0, 0, 0);border-style:dotted;}\n\n#blog-menu table {height:38px;background:transparent;}\n\n#blog-menu .on {color:rgb(238, 131, 163);}\n\n#blog-menu .off {color:rgb(119, 119, 119);}\n\n#blog-menu .bar {background:rgb(119, 119, 119);}\n\n\n#blog-profile .border {border-width:0px;border-style:solid;border-color:rgb(255, 255, 255);}\n\n#blog-profile .bg-head {height:5px;background:none;}\n\n#blog-profile .bg-body {padding:0px;background:transparent;}\n\n#blog-profile .bg-footer {height:30px;background:url(https://ssl.pstatic.net/static/blog/skin/100/bg-footer.png);}\n\n#blog-profile .col {color:rgb(85, 85, 85);}\n\n#blog-profile .icon {background-image:url(https://blogimgs.pstatic.net/nblog/skins/profile/0162_icon.gif);}\n\n#blog-profile .image {display:none;}\n\n#blog-profile .image img {width:161px;}\n\n#blog-profile .align {text-align:left;}\n\n\n\n* html #blog-profile .bg-footer { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://ssl.pstatic.net/static/blog/skin/100/bg-footer.png,sizingMethod=crop); }\n\n#blog-rss {height:27px;background-image:url(https://blogimgs.pstatic.net/nblog/skins/rss/0104_image_1.gif);}\n\n#blog-rss .rss1 {width:42px;height:14px;margin:8px 0 0 30px;}\n\n#blog-rss .rss2 {width:42px;height:14px;margin:8px 0 0 72px;}\n\n#blog-rss .rss3 {width:48px;height:14px;margin:8px 0 0 114px;}\n\n#post-area .post {border-width:0px;border-color:rgb(235, 235, 235);border-style:none;}\n\n#post-area .post-back {background:transparent;}\n\n#post-area .pcol1 {color:rgb(238, 131, 163);font-size:14px;}\n\n#post-area .pcol2 {color:rgb(85, 85, 85);}\n\n#post-area .pcol2b {background:rgb(85, 85, 85);}\n\n#post-area .cline {border-bottom-color:rgb(85, 85, 85);}\n\n#post-area .pcol3 {color:rgb(238, 131, 163);}\n\n#post-area .dline {border-top-width:1px;border-top-color:rgb(238, 131, 163);border-top-style:dotted;}\n\n#post-area .htl {width:15px;height:15px;background:transparent;}\n\n#post-area .htc {height:15px;background:transparent;}\n\n#post-area .htr {width:15px;height:15px;background:transparent;}\n\n#post-area .ftl {width:15px;height:15px;background:transparent;}\n\n#post-area .ftc {height:15px;background:transparent;}\n\n#post-area .ftr {width:15px;height:15px;background:transparent;}\n\n#post-area .bcl {width:15px;background:transparent;}\n\n#post-area .bcc {background:transparent;}\n\n#post-area .bcr {width:15px;background:transparent;}\n\n#post-area .ico1 {background:url(https://blogimgs.pstatic.net/nblog/skins/poststyle/0008_ico1_up.gif);}\n\n#post-area .ico2 {background:url(https://blogimgs.pstatic.net/nblog/skins/poststyle/0008_ico1_down.gif);}\n\n#post-area .ico3 {background:url(https://blogimgs.pstatic.net/nblog/skins/poststyle/0008_ico2.gif);}\n\n#post-area .comment {background:transparent;}\n\n#post-area .btn {background:url(https://blogimgs.pstatic.net/nblog/skins/poststyle/0000_input.png);}\n\n#post-area .btn-sympathy {background:url(https://blogimgs.pstatic.net/nblog/skins/poststyle/btn_sympathy_03.gif);}\n\n#post-area .btn_r {background:url(https://blogimgs.pstatic.net/nblog/skins/poststyle/btn_reply_default.gif);}\n\n\n\n* html #post-area .btn { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/poststyle/0000_input.png,sizingMethod=crop); }\n.post-back {background:transparent;}\n.pcol1 {color:rgb(238, 131, 163);font-size:14px;}\n.pcol2 {color:rgb(85, 85, 85);}\n.pcol2b {background:rgb(85, 85, 85);}\n.pcol3 {color:rgb(238, 131, 163);}\n.bcc {background:transparent;}\n#post-area .sline {border-bottom-color:rgb(238, 131, 163);}\n\n\r\n\t\r\n\t\r\n/*]]>*/\r\n</style>\r\n\r\n<script type="text/javascript" src="https://ssl.pstatic.net/t.static.blog/mylog/versioning//common/js/global/RemoveSubDomain-12d2f16_https.js"></script>\r\n<script>\r\n\r\n\r\n\r\n\r\n\r\n\r\nvar mylogURL = \'https://blog.naver.com\';\r\nvar adminURL = \'https://admin.blog.naver.com\';\r\nvar noteURL = \'https://note.naver.com\';\r\nvar itemURL = \'https://item.naver.com\';\r\nvar cafeURL = \'https://cafe.naver.com\';\r\nvar profileURL = \'https://blog.naver.com\';\r\nvar blogURL = \'https://blog.naver.com\';\r\nvar blogURLHttp = \'https://blog.naver.com\';\r\nvar prologueURL = \'https://blog.naver.com\';\r\nvar sectionURL = \'https://section.blog.naver.com\';\r\nvar memologURL = \'https://blog.naver.com\';\r\nvar lifeURL = \'https://lifelog.blog.naver.com\';\r\nvar uploadURL = \'https://upload.blog.naver.com\';\r\nvar imageURL = \'https://blogimgs.pstatic.net\';\r\nvar attachURL = \'https://blogfiles.pstatic.net\';\r\nvar thumbnailURL = \'https://blogthumb.pstatic.net\';\r\nvar nonCachedThumbnailURL = \'https://blogthumb.pstatic.net\';\r\nvar filetransURL = \'http://filetrans.blog.naver.com\';\r\nvar item2_bridgeURL = \'http://bridge.item2.naver.com\';\r\nvar idURL = \'http://nid.naver.com\';\r\nvar idURLSecret = \'https://nid.naver.com\';\r\nvar mapviewURL = \'http://mapview.naver.com\';\r\nvar exifURL = \'https://exif-blog.ssl.phinf.net\';\r\nvar viewerImageUrl = imageURL + "/blog20/blog/layout_photo/viewer/";\r\nvar domainURL = "";\r\nvar greenReviewCampaignURL = \'http://campaign.naver.com\';\r\nvar writeURL = \'https://blog.naver.com\';\r\nvar spiURL = \'https://ssl.pstatic.net/spi\';\r\nvar blogProfileThumbnailUrl=\'https://blogpfthumb-phinf.pstatic.net\';\r\nvar naverCommentStaticURL = \'https://ssl.pstatic.net/static.cbox\';\r\nvar naverCommentApiURL = \'https://apis.naver.com/commentBox/cbox9\';\r\nvar naverCommentApiProxyURL = \'https://apis.naver.com/commentBox/blogid\';\r\nvar itemImagesURL = \'https://blogimgs.pstatic.net/item\';\r\n\r\nvar sCssUrlForPhotoLayer = \'https://ssl.pstatic.net/t.static.blog/mylog/versioning//common/css/storyphoto_original_viewer-adf5d27_https.css\';\r\nvar commonStatDailyURL = \'https://blog.stat.naver.com\';\r\nvar baUrl = \'https://scv-blog.io.naver.com/jackpotlog/v1/logs\';\r\n\n\n\n\n\nvar blogId = \'hkh443\' || \'hkh443\';  \nvar userId = \'\'; \nvar userNo = \'\'; \nvar userNaverId = \'\';\nvar baUserKey = \'__UNKNOWN__\';\n\n\n\nvar isWritingBlocked = false;\nvar isWritingBlockedBySpamIP = false;\nvar isWritingBlockedBySpamIPManually = false;\nvar isLoggedIn = false;\nvar isShortestContentAreaWidth = false;\n\nvar blogOwner = false; \n\nvar blogNo = \'30551192\';\nvar nickName = \'\';\nvar isInitializingBlog = false;\nvar rightClickOpenYn = true;\nvar isMylogBlocked = false;\nvar isBlogBlock = false;\nvar blockOrWriteBlock = false;\nvar autoSourcingYn = true;\n\n\nvar isMemolog = false;\nvar isMemologList = false;\nvar isPrologue = false;\n\n\nvar isBlogMe = false;\n\nvar isUsingUrl = false;\n\n\nvar isRequestFromIPad = false;\n\n\nvar isOverIOS5_0Version = false;\nvar isOverAndroidJellybeanVersion = false;\nvar isCommingNaverApp = false;\nvar isUsingNaverKitkatEngine = false;\nvar isAndroidKitkatVersion = false;\n\nvar defaultSmartEditorVersion = 2;\n\nvar adContentLocation = "0";\n\n\n\r\n\r\n\r\n\r\nvar readOnlyStatus = false;\r\nvar readOnlyStatusAll = false;\r\nvar readOnlyLinkErrorMsg = \'죄송합니다. 블로그 서비스 점검 중입니다. \\n점검 시간 동안은 기능 이용이 제한됩니다. \\n자세한 내용은 블로그 홈 공지사항을 참고해주세요.\';\r\nvar readOnlyCommentMsg = \'12월 17일(월) 오전 0시~8시 서비스 점검으로 댓글 작성이 제한됩니다. \\n더욱 안정적인 서비스로 찾아뵙겠습니다. 불편하시더라도 조금만 기다려주세요.\';\r\nvar sIsTagReadOnly = \'\';\r\nvar sTagSorryText = \'죄송합니다. 태그 서비스 점검 중입니다.\\n점검 시간 동안은 일부 서비스 이용이 제한됩니다.\\n자세한 내용은 공지사항을 참조하세요.\';\r\nvar blogQuickPostingUseType = "NOT_SET"; \r\n\r\n\r\n\r\n\r\nvar isCommentReadOnly = false;\r\nvar sCommentReadOnlyBlockSubmit = \'죄송합니다. 블로그 댓글, 답글 서비스 점검 중에는 이용이 제한됩니다.\';\r\nvar sCommentReadOnlyWriteMsg = \'서비스 점검으로 댓글 작성이 제한됩니다.\\n더욱 안정적인 서비스로 찾아뵙겠습니다. 불편하시더라도 조금만 기다려주세요.\';\r\n \r\n\r\n\r\n\r\n\r\n\r\n\r\nvar isJeagleDebug = false;\r\n\r\n\r\n\r\n\r\n\r\nvar skinId = "0";\r\nvar skinType = "C";\r\n\r\nvar isEnglish = "false";\r\n\r\nvar areaCode = "11B10101";\r\nvar weatherType = "0";\r\n\r\nvar currencySign = "ALL";\r\n\r\nvar listNumVisitor = \'5\';\r\nvar isVisitorOpen = true;\r\nvar isCategoryOpen = true;\r\nvar writingMaterialListType = \'1\'\r\nvar previewCalType = \'\';\r\n\r\n\r\n\r\nvar oExternalWidget = [{\'teminationMessageHtml\':\'\',\'blockYn\':false,\'blogId\':\'hkh443\',\'reversedWidgetCode\':\'E3%aF2%C3%E3%F2%+22%22%D3%tla+22%006D3%hB3%pma62%061D3%wB3%pma62%258345I-f54e95e5e27f0eab-103-0VD3%dIecartB3%pma62%D3%dIbusF3%258345F2%srennabF2%moc.gnapuoc.srentrap-sdaF2%F2%A3%sptth22%D3%crs+gmiC3%E3%22%lru-efasnu22%D3%yciloprerrefer++22%P7NlbcF2%gn.apuocF2%F2%A3%sptth22%D3%ferh+22%knalb_22%D3%tegrat+aC3%\',\'serviceTerminated\':false,\'seq\':1}];\r\n\r\n\r\nvar calType = "";\r\n\r\n\r\nvar curLog = \'https://blog.naver.com\';\r\nvar playerType = \'0\';\r\nvar playerDesign = \'1\';\r\n\r\n\r\nvar isCommentOpen = false;\r\nvar listNumComment = 5;\r\n\r\n\r\nvar isBuddyOpen = false;\r\n\r\n\r\n\r\nvar userSelectMenu = \'\';\r\n\r\n\r\nvar visitorgpData = \'\';\r\nvar vigitorSetUrl = \'\';\r\nvar vigitorPropUrl = \'/versioning//common/swf/Widget/visitorGP/VisitorGP-50a2c61.xml\';\r\nvar visitorgp_vars = {\r\n\tsetUrl    : vigitorSetUrl,\r\n\treq_url   : \'/NVisitorgp4Ajax.naver?blogId=\' + blogId,\r\n\tprop_url  : vigitorPropUrl,\r\n\tgraphType : visitorgpData,\r\n\tflashvars : function(){\r\n\t\treturn "req_url=" + this.req_url +"&prop_url=" + this.prop_url +"&graphType=" + this.graphType;\r\n\t},\r\n\theight    : 121\r\n};\r\n\r\n\r\n\r\nvar watchData = \'\';\r\nvar watch_design = {\r\n\tname    : watchData.split(\'|\')[0],\r\n\tfont    : watchData.split(\'|\')[1],\r\n\tcolor   : watchData.split(\'|\')[2],\r\n\tbgcolor : watchData.split(\'|\')[3]\r\n}\r\nvar watch_vars = {\r\n\tblogId : blogId,\r\n\tskinType : skinType,\r\n\tskinId : skinId\r\n}\r\n\r\n\r\nvar serviceId = \'\';\r\nvar naverId = \'\';\r\nvar happyBeanApiURL = \'\';\r\nvar reqparam = \'\';\r\nvar HAPPYBEAN_API_URL = "";\r\nvar HAPPYBEAN_FUND_URL = "";\r\n//var HAPPYBEAN_MY_URL   = "";\r\nvar HAPPYBEAN_DONATION_URL = "";\r\n\r\n\r\n\r\n\r\nvar selectCategoryNo = "1";\r\n\r\n\r\nvar aNonWidget = [\'rss\', \'powered\',\'adpost\',\'buddyconnect\',\'greenreview\'];\r\n<!-- var aWidget = [\'gnb\', \'externalwidget\',\'music\'];  -->\r\nvar aWidget = [];\r\n\r\n\r\naWidget.push(\'title\');\r\n\r\naWidget.push(\'menu\');\r\n\r\naWidget.push(\'category\');\r\n\r\naWidget.push(\'stat\');\r\n\r\naWidget.push(\'profile\');\r\n\r\naWidget.push(\'search\');\r\n\r\naWidget.push(\'rss\');\r\n\r\naWidget.push(\'1\');\r\n\r\naWidget.push(\'content\');\r\n\r\naWidget.push(\'gnb\');\r\n\r\naWidget.push(\'externalwidget\');\r\n\r\nvar bIsRemocon = false;\r\nvar bIsPreview = document.location.href.indexOf("PostPreview.nhn") > -1 || document.location.href.indexOf("MemologMemoPreview.nhn") > -1;\r\n\r\nvar isTopLayoutEmpty = false;\r\n\r\nvar openSideType = "1";\r\nvar foldSideType = "2";\r\n\r\nvar g_ContentShareObject = {\r\n\tadPostPreview : false,\r\n\tadPostPreviewSide : false,\r\n\tadPostPreviewContent : false,\r\n\tadPostAlign : "",\r\n\tadPostCount : ""\r\n};\r\n\r\nvar blogDomainUrl = "";\r\nvar sAjaxFlashUrl = \'/versioning//common/lib/ajax.flash/ajax-885363e.swf\';\r\nvar isHappyBeanLeverage = false;\r\n\r\n\r\nvar doc = document.documentElement;\r\ndoc.setAttribute(\'data-useragent\',navigator.userAgent);\r\nvar gbIsNotOpenBlogUser = "false" === "true";\r\nvar gbIsNPayAccepted = "false";\r\nvar gbIsPayAcceptedOrBefore = "false";\r\n</script>\r\n\r\n<script type="text/javascript" src="https://ssl.pstatic.net/t.static.blog/mylog/versioning/Jindo152-313837964_https.js" charset="utf-8"></script>\r\n<script type="text/javascript" src="https://ssl.pstatic.net/t.static.blog/mylog/versioning/LayoutTopCommon-918232278_https.js" charset="UTF-8"></script>\r\n<script type="text/javascript" src="https://ssl.pstatic.net/t.static.blog/mylog/versioning/JindoComponent-190469086_https.js" charset="utf-8"></script>\r\n\r\n\n\n\n\t\n\t\t<meta name="robots" content="index,follow"/>\n\t\n\t\n\n\n\n<meta http-equiv=\'imagetoolbar\' content=\'no\'/>\n\n\n\n\n\t\n\n\n<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />\n<meta property="og:type" content="article"/>\

In [53]:
def get_redirect(url):
    crawling_waiting_time()
    import requests

    # pretend headers with private mode
    
    # headers = {
    #     "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    #     "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
    #     "Accept-Language": "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7",
    #     "Referer": "https://blog.naver.com/",
    #     "Connection": "keep-alive",
    #     "Cache-Control": "max-age=0",
    #     "Upgrade-Insecure-Requests": "1",
    # }
    try:
        location = ''
        user = UserAgent().random
        headers = {
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
            "Accept-Language": "ko-KR,ko;q=0.8,en-US;q=0.5,en;q=0.3"
        }
        r = requests.get(url, headers=headers, allow_redirects=False, timeout=10)
        print(r.headers)
        if 'location' in r.headers:
            location = r.headers['location']
        elif 'Location' in r.headers:
            location = r.headers['Location']
        return location
    except:
        return ''
    # r = requests.get(url, headers=headers, allow_redirects=False, timeout=10)
    # return r.url

In [54]:
def get_item_name(url):
    import urllib.parse
    try:
        return urllib.parse.unquote_plus(url.split('q=')[1].split('&src=')[0])
    except:
        try:
            return urllib.parse.unquote_plus(url.split('&pageKey=')[1].split('&')[0])
        except:
            return ''

In [62]:
def get_href(html):
    from bs4 import BeautifulSoup
    soup = BeautifulSoup(html, 'html.parser')
    elems = soup.find_all("a", {"class":"se-link"})
    print(len(elems))
    # output = [get_redirect(x.get('href')) for x in elems]
    # print(output)
    output_dict = {}
    for x in elems:
        if x != '':
            href = x.get('href')
            print(f'href : {href}')
            redir = get_redirect(href)
            print(f' - redir : {redir}')
            if 'link.coupang' in redir:
                redir = get_redirect(redir)
                print(f' - (re)redir : {redir}')
            name = get_item_name(redir).replace(u'\xa0', u' ')
            output_dict[x.get_text()] = name

    output_dict = {x for x in output_dict.items() if x[1] != ''}
    return output_dict

In [63]:
links = get_href(html)
links

18
href : https://vvd.bz/jEV
{'Date': 'Fri, 07 Feb 2025 08:32:51 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'Set-Cookie': 'linkAgentKey=653a85a2ed9b46c1b7b7bc8dcd202829; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:32:51 GMT; Path=/; Secure; HttpOnly', 'Location': 'https://link.coupang.com/a/cdnhva', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'Content-Language': 'ko', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir : https://link.coupang.com/a/cdnhva
{'Content-Length': '0', 'Server': 'istio-envoy', 'x-ua-compatible': 'IE=edge', 'Cache-Control': 'no-store, no-cache, must-revalidate', 'x-robots-tag': 'noindex, nofollow, noindex, nofollow', 'Location': 'https://www.coupang.com/np/search?q=%EB%A7%88%EB%A3%A8%EC%A5%AC%20%EC%B9%B4%EB%82%98%EC%95%84%EB%AF%B8%20%EC%9B%90%EC%A0%81%EC%99%B8%EC%84%A0%20%EC%84%B8%EB%9D%BC%EB%AF%B9%20%EC%84%9D%EC%87%A0&src=1139000&spec=10799999&addtag=200&ctag=%EB%A7%88%EB%A3%A8%EC%A5%AC%20%EC%B9%B4%EB%82%98%EC%95%84%EB%AF%B8%20%EC%9B%90%EC%A0%81%EC%99%B8%EC%84%A0%20%EC%84%B8%EB%9D%BC%EB%AF%B9%20%EC%84%9D%EC%87%A0&lptag=AF9131142&itime=20250207173253&pageType=SEARCH&pageValue=%EB%A7%88%EB%A3%A8%EC%A5%AC%20%EC%B9%B4%EB%82%98%EC%95%84%EB%AF%B8%20%EC%9B%90%EC%A0%81%EC%99%B8%EC%84%A0%20%EC%84%B8%EB%9D%BC%EB%AF%B9%20%EC%84%9D%EC%87%A0&wPcid=17389171733391763253036&wRef=&wTime=20250207173253&redirect=landing&traceid=V0-181-73836980eeebdfa6&mcid=af672191372e4f208a0f2d2cf7fa1d7b&placementid=&campaignid=&contentcategory=&imgsize=&tsource=&pageid=&deviceid=&token=&contenttype=&subid=&impressionid=&campaigntype=&requestid=&contentkeyword=&subparam=', 'Content-Language': 'ko', 'x-envoy-upstream-service-time': '1', 'x-envoy-decorator-operation': ':0/*', 'Date': 'Fri, 07 Feb 2025 08:32:53 GMT', 'Connection': 'keep-alive', 'Set-Cookie': 'member_srl=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/, SAID=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/; HttpOnly, PCID=17389171733381189559021; Max-Age=315360000; Expires=Mon, 05 Feb 2035 08:32:53 GMT; Domain=coupang.com; Path=/, MARKETID=17389171733381189559021; Secure; HttpOnly; SameSite=None; Expires=Wed, 06-Feb-2030 17:32:53 KST; Domain=.coupang.com; Path=/, member_srl=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/, SAID=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/; HttpOnly, PCID=17389171733391763253036; Max-Age=315360000; Expires=Mon, 05 Feb 2035 08:32:53 GMT; Domain=coupang.com; Path=/, MARKETID=17389171733381189559021; Secure; HttpOnly; SameSite=None; Expires=Wed, 06-Feb-2030 17:32:53 KST; Domain=.coupang.com; Path=/, trac_src=1139000; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:32:53 GMT; Domain=coupang.com; Path=/, trac_spec=10799999; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:32:53 GMT; Domain=coupang.com; Path=/, trac_addtag=200; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:32:53 GMT; Domain=coupang.com; Path=/, trac_ctag=%EB%A7%88%EB%A3%A8%EC%A5%AC+%EC%B9%B4%EB%82%98%EC%95%84%EB%AF%B8+%EC%9B%90%EC%A0%81%EC%99%B8%EC%84%A0+%EC%84%B8%EB%9D%BC%EB%AF%B9+%EC%84%9D%EC%87%A0; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:32:53 GMT; Domain=coupang.com; Path=/, trac_lptag=AF9131142; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:32:53 GMT; Domain=coupang.com; Path=/, trac_itime=20250207173253; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:32:53 GMT; Domain=coupang.com; Path=/, _abck=ED65A6C47F268DCE0E2A7E0DA5C28E69~-1~YAAQfCE1F26NDpaUAQAAk1iK3w0WDzbQmp6W+XzpIbSZZiuEFnGcRcEsTX+c5Rr/5A1ROa3uIUxPrCARYJG01hugN5tBBQ9dN8V53IvJSPNKN94Qet/o63s4tB5PmTbdhieh+oOuVKZZzSpKtsnLR6dHgBxS4mxaaa31ZNMrR71mJ11h2F/lZk+vWHoJNZ/zIemVobw1CvaZ0WRQ+xhjPqiOs3ErRRqVAMJ+P3KRjwtgDG/xJ2slYsZk3H/hMIHa9hRbOQJkuaqbVHZq/sVi4wET6/MJtSbkdC4z/VhxpoyDkOUhWxHjfu52j+dlOvAXFaQymWYVUGXWv5K5tCTM9xq74N7/T4sapM5MPB5mmmkfwTB7plL+EAN5VpAMPD3B0gJFwK1FE2cBs1iXSDH8gNGC7xByGRbyaMCSteI=~-1~-1~-1; Domain=.coupang.com; Path=/; Expires=Sat, 07 Feb 2026 08:32:53 GMT; Max-Age=31536000; Secure, bm_sz=448F8F9C558C388CF05A893BB04DA2F0~YAAQfCE1F2+NDpaUAQAAk1iK3xp3vGZisq/xPOYRa5CpgwJ9Flm+xdii1wM9PXWdnWIwRnC7IBAodc3GhaX2byMDM7pAQnu59IKi6Q/tQSDftuH65t5QSk9gadD5ydVTjyp88Vs4q5++2Uck9N4YAMb63AXtpL0aM2gCuoFZluCO0hNl7CUu+66vi6XMyn+K7d4nxaWHd9RlZdDU/x5m7ilbkzsa9gIw7YGANd8YBWWa6hilEzIIUwkfLdXCSqleEKR8Cac3FDSv/TQpXQKFjZ0oqwJBkQqdQND3xtN0eZXJJ/r8xXtmgNQhzVzImiEP82elOMqRUY20tQJYQem0EGLDAO19k3Mdi8fu6V5LJg==~3617076~3289401; Domain=.coupang.com; Path=/; Expires=Fri, 07 Feb 2025 12:32:53 GMT; Max-Age=14400', 'Strict-Transport-Security': 'max-age=31536000'}
 - (re)redir : https://www.coupang.com/np/search?q=%EB%A7%88%EB%A3%A8%EC%A5%AC%20%EC%B9%B4%EB%82%98%EC%95%84%EB%AF%B8%20%EC%9B%90%EC%A0%81%EC%99%B8%EC%84%A0%20%EC%84%B8%EB%9D%BC%EB%AF%B9%20%EC%84%9D%EC%87%A0&src=1139000&spec=10799999&addtag=200&ctag=%EB%A7%88%EB%A3%A8%EC%A5%AC%20%EC%B9%B4%EB%82%98%EC%95%84%EB%AF%B8%20%EC%9B%90%EC%A0%81%EC%99%B8%EC%84%A0%20%EC%84%B8%EB%9D%BC%EB%AF%B9%20%EC%84%9D%EC%87%A0&lptag=AF9131142&itime=20250207173253&pageType=SEARCH&pageValue=%EB%A7%88%EB%A3%A8%EC%A5%AC%20%EC%B9%B4%EB%82%98%EC%95%84%EB%AF%B8%20%EC%9B%90%EC%A0%81%EC%99%B8%EC%84%A0%20%EC%84%B8%EB%9D%BC%EB%AF%B9%20%EC%84%9D%EC%87%A0&wPcid=17389171733391763253036&wRef=&wTime=20250207173253&redirect=landing&traceid=V0-181-73836980eeebdfa6&mcid=af672191372e4f208a0f2d2cf7fa1d7b&placementid=&campaignid=&contentcategory=&imgsize=&tsource=&pageid=&deviceid=&token=&contenttype=&subid=&impressionid=&campaigntype=&requestid=&contentkeyword=&subparam=
href : https://vvd.bz/jEY
{'Date': 'Fri, 07 Feb 2025 08:32:55 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'Set-Cookie': 'linkAgentKey=229c63004aea4e39b2bbe781aef3f0e2; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:32:55 GMT; Path=/; Secure; HttpOnly', 'Location': 'https://link.coupang.com/a/cdnlu5', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'Content-Language': 'ko', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir : https://link.coupang.com/a/cdnlu5
{'Content-Length': '0', 'Server': 'istio-envoy', 'x-ua-compatible': 'IE=edge', 'Cache-Control': 'no-store, no-cache, must-revalidate', 'x-robots-tag': 'noindex, nofollow, noindex, nofollow', 'Location': 'https://www.coupang.com/np/search?q=8mm%20%EC%A7%84%EC%A3%BC%20%EB%AA%A9%EA%B1%B8%EC%9D%B4&src=1139000&spec=10799999&addtag=200&ctag=8mm%20%EC%A7%84%EC%A3%BC%20%EB%AA%A9%EA%B1%B8%EC%9D%B4&lptag=AF9131142&itime=20250207173258&pageType=SEARCH&pageValue=8mm%20%EC%A7%84%EC%A3%BC%20%EB%AA%A9%EA%B1%B8%EC%9D%B4&wPcid=17389171780302312919459&wRef=&wTime=20250207173258&redirect=landing&traceid=V0-181-732e97a771afa5a4&mcid=46be199e68a14fef96a78514cbe1296b&placementid=&campaignid=&contentcategory=&imgsize=&tsource=&pageid=&deviceid=&token=&contenttype=&subid=&impressionid=&campaigntype=&requestid=&contentkeyword=&subparam=', 'Content-Language': 'ko', 'x-envoy-upstream-service-time': '2', 'x-envoy-decorator-operation': ':0/*', 'Date': 'Fri, 07 Feb 2025 08:32:58 GMT', 'Connection': 'keep-alive', 'Set-Cookie': 'member_srl=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/, SAID=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/; HttpOnly, PCID=17389171780303735509405; Max-Age=315360000; Expires=Mon, 05 Feb 2035 08:32:58 GMT; Domain=coupang.com; Path=/, MARKETID=17389171780303735509405; Secure; HttpOnly; SameSite=None; Expires=Wed, 06-Feb-2030 17:32:58 KST; Domain=.coupang.com; Path=/, member_srl=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/, SAID=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/; HttpOnly, PCID=17389171780302312919459; Max-Age=315360000; Expires=Mon, 05 Feb 2035 08:32:58 GMT; Domain=coupang.com; Path=/, MARKETID=17389171780303735509405; Secure; HttpOnly; SameSite=None; Expires=Wed, 06-Feb-2030 17:32:58 KST; Domain=.coupang.com; Path=/, trac_src=1139000; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:32:58 GMT; Domain=coupang.com; Path=/, trac_spec=10799999; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:32:58 GMT; Domain=coupang.com; Path=/, trac_addtag=200; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:32:58 GMT; Domain=coupang.com; Path=/, trac_ctag=8mm+%EC%A7%84%EC%A3%BC+%EB%AA%A9%EA%B1%B8%EC%9D%B4; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:32:58 GMT; Domain=coupang.com; Path=/, trac_lptag=AF9131142; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:32:58 GMT; Domain=coupang.com; Path=/, trac_itime=20250207173258; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:32:58 GMT; Domain=coupang.com; Path=/, _abck=2588B998FEB20F035E3175C632765B7B~-1~YAAQhCE1F1wJYLqUAQAANmuK3w0ItEUO7StCjVTkXO0XZG8wt4kLYFODrnLd7NbDXDIPs8hROQLByJg6NCKZ9mmrz2cpzWALiYt1iRyJozhhFErRF2LovLYKzPDlmeF5a2VDC6mpu/Yz56gTD/ddGhITT5T4bGR/ro2dRcWHb4HFmAaoSC/RTZqWILo3/fWhz5PrfHy3TpLBSa4BrB1t0OrIbVKVBRwf7BFQGCtEuW+qxc5kQSATlOIdCQoBg/s4/G+25wCaKNtxZoyl/BkAA4p109/i48CjzWAgP/v1k1iu784Mvu0T1FiMW0klFL9q/Ybg4n+mVecHLNxE9uikFSSeYLfcZ1khvCd0kw7gy/CNb6UXLIRReNRaS7leJ8749+s7vcsEMjylCG6hHMgmgPTKndnqCSYu28i7EuI=~-1~-1~-1; Domain=.coupang.com; Path=/; Expires=Sat, 07 Feb 2026 08:32:58 GMT; Max-Age=31536000; Secure, bm_sz=3D7D20002605991C4A93C51B1881659F~YAAQhCE1F10JYLqUAQAANmuK3xquKd+vDB++sGlzIg7YLDpFE0QZfeMem7E8B5/EefN21DeIlaS0TKYbCb4es5rIxAjV0IZW06wBowDdD7HgOewUZgD7xL5YnIvgk5bGtJD+Jy02qZOgQJLf55CfrYtyZtQuoYmhNRE8iH4OYmB7Ch2n2IykixrIPhYW3ODP0dkk3hjB0kYZM3XOGvcCwj8cHUVJznCPbGitCH3csbNMAS3jdmlpXi58iy9THxMqEwXKsUne2Cj8y9tC/TIQCZfWBLz/Za8tskliB7MQkiYpjP6wBZ74PuMHPBPISXmc8iO9kz7f5aNW/i/EHBYKc5Bped1AQ3X4rohOE+Fb3Q==~3618103~4404279; Domain=.coupang.com; Path=/; Expires=Fri, 07 Feb 2025 12:32:57 GMT; Max-Age=14399', 'Strict-Transport-Security': 'max-age=31536000'}
 - (re)redir : https://www.coupang.com/np/search?q=8mm%20%EC%A7%84%EC%A3%BC%20%EB%AA%A9%EA%B1%B8%EC%9D%B4&src=1139000&spec=10799999&addtag=200&ctag=8mm%20%EC%A7%84%EC%A3%BC%20%EB%AA%A9%EA%B1%B8%EC%9D%B4&lptag=AF9131142&itime=20250207173258&pageType=SEARCH&pageValue=8mm%20%EC%A7%84%EC%A3%BC%20%EB%AA%A9%EA%B1%B8%EC%9D%B4&wPcid=17389171780302312919459&wRef=&wTime=20250207173258&redirect=landing&traceid=V0-181-732e97a771afa5a4&mcid=46be199e68a14fef96a78514cbe1296b&placementid=&campaignid=&contentcategory=&imgsize=&tsource=&pageid=&deviceid=&token=&contenttype=&subid=&impressionid=&campaigntype=&requestid=&contentkeyword=&subparam=
href : https://vvd.bz/jEy
{'Date': 'Fri, 07 Feb 2025 08:33:01 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'Set-Cookie': 'linkAgentKey=773571215156446c9c0f24dce5581e82; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:33:01 GMT; Path=/; Secure; HttpOnly', 'Location': 'https://link.coupang.com/a/cdn4zA', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'Content-Language': 'ko', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir : https://link.coupang.com/a/cdn4zA
{'Content-Length': '0', 'Server': 'istio-envoy', 'x-ua-compatible': 'IE=edge', 'Cache-Control': 'no-store, no-cache, must-revalidate', 'x-robots-tag': 'noindex, nofollow, noindex, nofollow', 'Location': 'https://www.coupang.com/np/search?q=%ED%84%B0%ED%82%A4%EC%84%9D%20%EB%AA%A9%EA%B1%B8%EC%9D%B4&src=1139000&spec=10799999&addtag=200&ctag=%ED%84%B0%ED%82%A4%EC%84%9D%20%EB%AA%A9%EA%B1%B8%EC%9D%B4&lptag=AF9131142&itime=20250207173302&pageType=SEARCH&pageValue=%ED%84%B0%ED%82%A4%EC%84%9D%20%EB%AA%A9%EA%B1%B8%EC%9D%B4&wPcid=17389171826278188553506&wRef=&wTime=20250207173302&redirect=landing&traceid=V0-181-e8ed1ce2a6c63161&mcid=fdf128b7b6984b5eb5cf960ce1ff0a8b&placementid=&campaignid=&contentcategory=&imgsize=&tsource=&pageid=&deviceid=&token=&contenttype=&subid=&impressionid=&campaigntype=&requestid=&contentkeyword=&subparam=', 'Content-Language': 'ko', 'x-envoy-upstream-service-time': '1', 'x-envoy-decorator-operation': ':0/*', 'Date': 'Fri, 07 Feb 2025 08:33:02 GMT', 'Connection': 'keep-alive', 'Set-Cookie': 'member_srl=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/, SAID=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/; HttpOnly, PCID=17389171826266533386318; Max-Age=315360000; Expires=Mon, 05 Feb 2035 08:33:02 GMT; Domain=coupang.com; Path=/, MARKETID=17389171826266533386318; Secure; HttpOnly; SameSite=None; Expires=Wed, 06-Feb-2030 17:33:02 KST; Domain=.coupang.com; Path=/, member_srl=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/, SAID=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/; HttpOnly, PCID=17389171826278188553506; Max-Age=315360000; Expires=Mon, 05 Feb 2035 08:33:02 GMT; Domain=coupang.com; Path=/, MARKETID=17389171826266533386318; Secure; HttpOnly; SameSite=None; Expires=Wed, 06-Feb-2030 17:33:02 KST; Domain=.coupang.com; Path=/, trac_src=1139000; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:33:02 GMT; Domain=coupang.com; Path=/, trac_spec=10799999; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:33:02 GMT; Domain=coupang.com; Path=/, trac_addtag=200; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:33:02 GMT; Domain=coupang.com; Path=/, trac_ctag=%ED%84%B0%ED%82%A4%EC%84%9D+%EB%AA%A9%EA%B1%B8%EC%9D%B4; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:33:02 GMT; Domain=coupang.com; Path=/, trac_lptag=AF9131142; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:33:02 GMT; Domain=coupang.com; Path=/, trac_itime=20250207173302; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:33:02 GMT; Domain=coupang.com; Path=/, _abck=DE1F7951A2F39BDB23DE9740EEDF24A0~-1~YAAQrCE1F8Pyz86UAQAA4nyK3w2DC4iD7bCgPPBEiwwamaoz6dp+KA+venbyQrLb7qfdkSbuwVpZHLSgLwRO2pNruZU88KvJHY0tJ7K01q9GJECQJkPV7ak+DX3Zrfo69XmJBIjOqqy6mBu0XAykz+uxaDHYK8az6e3JPVRLuo3pWEiY13nxEHq3iSRg1asxE//apwiPRJD4hw1p/7p6kX1wTvFmOqQrILka5MkE8inaIKB6y82UZ42E0cGIe+o82bIx2f9SGfjJwhjQ8GuC60TZyvtOOuYpNO++OtUHgyw/4/vgfmNo4TzPq+1YoBw2WMYcws3IjGlWbs+grTEiVdVY6IE+ZWCaQJ4bkvZxJDHnJhYv9EH7r4IOKbRGMjcfP22zhLXHDAIS1oo9VEYRSeN/FK1XbrfszEZcDIU=~-1~-1~-1; Domain=.coupang.com; Path=/; Expires=Sat, 07 Feb 2026 08:33:02 GMT; Max-Age=31536000; Secure, bm_sz=6300BB9088BE73B8891C54C46B876E53~YAAQrCE1F8Tyz86UAQAA4nyK3xpsrn3jZNNyfdh7PANyxytMc4xozHOD/qcrB0bPHIyvq4P61/59liKeRSOu2HhIZ+S+j4pZwHbNPgJFgQTjS1ByP7WuqwM5L1f+rO1PK5rFawaGwCzY1I2Pv18fwrZVTzstNktVa+FRsG6Oq+dMqC2sbiewJYIXq+uN5uvqAFlbrPN2jQICmsbJj4S//qpp4pbOscbHGKJGJYEzd1ha/2iCmuqwSotxzdLYLc8TnamCUoVakwQwSrd71KOS3l8jjgUdmin0OjSWo353sSCADCrE7JlsMU6uKC5HebZDTR85N6PKVOiPBn1pE7E/xnzi0hgFFtrADXmXmeQwTQ==~3293489~4469049; Domain=.coupang.com; Path=/; Expires=Fri, 07 Feb 2025 12:33:02 GMT; Max-Age=14400', 'Strict-Transport-Security': 'max-age=31536000'}
 - (re)redir : https://www.coupang.com/np/search?q=%ED%84%B0%ED%82%A4%EC%84%9D%20%EB%AA%A9%EA%B1%B8%EC%9D%B4&src=1139000&spec=10799999&addtag=200&ctag=%ED%84%B0%ED%82%A4%EC%84%9D%20%EB%AA%A9%EA%B1%B8%EC%9D%B4&lptag=AF9131142&itime=20250207173302&pageType=SEARCH&pageValue=%ED%84%B0%ED%82%A4%EC%84%9D%20%EB%AA%A9%EA%B1%B8%EC%9D%B4&wPcid=17389171826278188553506&wRef=&wTime=20250207173302&redirect=landing&traceid=V0-181-e8ed1ce2a6c63161&mcid=fdf128b7b6984b5eb5cf960ce1ff0a8b&placementid=&campaignid=&contentcategory=&imgsize=&tsource=&pageid=&deviceid=&token=&contenttype=&subid=&impressionid=&campaigntype=&requestid=&contentkeyword=&subparam=
href : https://vvd.bz/jEw
{'Date': 'Fri, 07 Feb 2025 08:33:04 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'Set-Cookie': 'linkAgentKey=9cb43d1eb75540f8b14fb57e23b1a242; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:33:04 GMT; Path=/; Secure; HttpOnly', 'Location': 'https://link.coupang.com/a/cdnZ0S', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'Content-Language': 'ko', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir : https://link.coupang.com/a/cdnZ0S

{('\u200b', '킬리안 러브 돈 비 샤이 향수'),
 ('▶괄사 마사저 보러가기', '미니 괄사'),
 ('▶귀걸이 보러가기', '왕진주귀걸이'),
 ('▶목걸이 보러가기', '터키석 목걸이'),
 ('▶선글라스 보러가기', 'CARIN KRISTEN  선글라스'),
 ('▶최화정 레몬 즙짜개 보러가기', '드림팜 플루서'),
 ('▶최화정 블러셔 보러가기', '조르지오 아르마니 a블러쉬'),
 ('▶최화정 석쇠 보러가기', '마루쥬 카나아미 원적외선 세라믹 석쇠'),
 ('▶최화정 아로마 오일 보러가기', '피몽쉐 리버티'),
 ('▶최화정 투명지갑 보러가기', '투명 동전지갑 파우치'),
 ('▶최화정 하트 찍찍이 보러가기', '하트 모양 벨크로 찍찍이'),
 ('▶최화정 핸드크림 보러가기', '블리쉐던 핸드크림'),
 ('▶최화정 향수 보러가기', '바이레도 블랑쉬 EDP 50ml')}

In [41]:
d3 = df3.to_dict()
d3[0].content

b'\r\n\r\n\r\n\r\n\r\n<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\r\n<html lang="ko">\r\n<head>\r\n<meta http-equiv="Pragma" content="no-cache" />\r\n<meta http-equiv="Expires" content="-1" />\r\n\r\n<meta name="referrer" content="always" />\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n<!--[if ie]>\r\n<style type="text/css">\r\nhtml {overflow: scroll; overflow-x: auto;}\r\n</style>\r\n<![endif]-->\r\n\r\n<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/t.static.blog/mylog/versioning/LayoutTopCommon-233548907_https.css" charset="UTF-8" />\r\n<link rel="stylesheet" type="text/css" href="https://ssl.pstatic.net/t.static.blog/mylog/versioning//common/css/music/player-d3fc09e_https.css">\r\n\r\n<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?3" />\r\n\n\n\n\n\n \n\n\t\n\t\t<meta property="og:title" content="\xec\xa0\x84\xec\xb0\xb8\xec\x8b\x9c \xea\xb9\x80\xec\x95\x84\xec\x98\x81 \xed\x99\x94\xeb\xb3\x91 \xed\x99\x88\xec\x95\xa4\xed\x95\x98\xeb\xb9\x84 \xeb\x8f\x84\xec\x9e\x90\xea\xb8\xb0\xed\x99\x94\xeb\xb3\x91 \xec\x84\xb8\xeb\x9d\xbc\xeb\xaf\xb9 \xec\x9d\xb8\xed\x85\x8c\xeb\xa6\xac\xec\x96\xb4 \xea\xb3\xa0\xeb\xa6\xac\xed\x98\x95"/>\n\n\t\t\n\t\t\t\n\t\t\t\n\t\t\t<meta property="og:image" content="https://blogthumb.pstatic.net/MjAyNTAyMDZfMjU5/MDAxNzM4ODMwNTk1MTQ1.9EEIXVhkSBr8-Ri8HWoxQQDMGuTBIExGLIq-GfPZtpkg.1V3_KOjDGMIby4jn3GY23pYEDwvbWXBUxh_YMDQ3sx8g.PNG/image.png?type=w2"/>\n\t\t\t\n\t\t\n        <meta property="og:description" content="\xec\xa0\x84\xec\xb0\xb8\xec\x8b\x9c \xea\xb9\x80\xec\x95\x84\xec\x98\x81 \xed\x99\x94\xeb\xb3\x91 \xed\x99\x88\xec\x95\xa4\xed\x95\x98\xeb\xb9\x84 \xeb\x8f\x84\xec\x9e\x90\xea\xb8\xb0 \xed\x99\x94\xeb\xb3\x91 \xec\x84\xb8\xeb\x9d\xbc\xeb\xaf\xb9 \xec\x9d\xb8\xed\x85\x8c\xeb\xa6\xac\xec\x96\xb4 \xea\xb3\xa0\xeb\xa6\xac\xed\x98\x95 MBC \xec\x98\x88\xeb\x8a\xa5 \xed\x94\x84\xeb\xa1\x9c\xea\xb7\xb8\xeb\x9e\xa8 \xec\xa0\x84\xec\xa7\x80\xec\xa0\x81 \xec\xb0\xb8\xea\xb2\xac \xec\x8b\x9c\xec\xa0\x90..."/>\n\n\t\t\n\t\t\t<meta property="og:url" content="https://blog.naver.com/bcf5qp11/223750032612"/>\n\t\t\n\t\n\t\n\n<meta property="me:feed:serviceId" content="blog" />\r\n<style type="text/css">\r\n/*<![CDATA[*/\r\n\n\nbody {background-color:rgb(226, 226, 226);background-image:url(https://ssl.pstatic.net/static/blog/skin/108/body.png);}\n#head-skin {background-image:url(https://ssl.pstatic.net/static/blog/skin/108/head-skin.png);}\n\n\n#whole-border {border-width:0px;border-color:rgb(0, 0, 0);border-style:solid;background:transparent;}\n#whole-head {height:0;background:transparent;}\n#whole-body {padding:0 8px;background:transparent;}\n#whole-footer {height:0;background:transparent;}\n\n\n#wrapper .side-border {border-width:0;border-style:solid;border-color:rgb(0, 0, 0);border:0;}\n#wrapper .side-head {height:8px;background:transparent;}\n#wrapper .side-body {padding:0;background:transparent;}\n#wrapper .side-footer {height:8px;background:transparent;}\n\n* html #wrapper .side-head { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://ssl.pstatic.net/static/blog/skin/108/side-head.png,sizingMethod=crop); }\n* html #wrapper .side-footer { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://ssl.pstatic.net/static/blog/skin/108/side-footer.png,sizingMethod=crop); }\n\n#wrapper .cm-col1 {color:rgb(68, 68, 68);}\n#wrapper .cm-arw {background:rgb(68, 68, 68);}\n#wrapper div.line {border-top-color:rgb(68, 68, 68);}\n#wrapper .cm-border {border-width:0px;border-style:solid;border-color:rgb(0, 0, 0);}\n#wrapper .cm-head {height:25px;background:transparent;}\n#wrapper .cm-body {background:transparent;}\n#wrapper .cm-footer {height:0;background:transparent;}\n#wrapper .cm-icol {color:rgb(51, 51, 51);}\n#wrapper h3 {margin-left:14px;bottom:4px;}\n#wrapper .cmore {bottom:4px;}\n#blog-category .listimage {background-image:url(https://blogimgs.pstatic.net/nblog/skins/infobox/0002_arw.gif);}\n#wrapper .buddyup {background-image:url(https://blogimgs.pstatic.net/nblog/skins/infobox/0002_icon_up.gif);}\n#wrapper .buddydw {background-image:url(https://blogimgs.pstatic.net/nblog/skins/infobox/0002_icon_down.gif);}\n#blog-category .f_icoclosed {background-image:url(https://blogimgs.pstatic.net/nblog/skins/infobox/ico_f_closed_l.gif) !important;}\n#blog-category .f_icoopen {background-image:url(https://blogimgs.pstatic.net/nblog/skins/infobox/ico_f_open_l.gif) !important;}\n#blog-category ul li.depth2 {background-image:url(https://blogimgs.pstatic.net/nblog/skins/infobox/ico_depth2_l.gif) !important;}\n\n\n#blog-gnb .link {color:rgb(153, 153, 153);}\n#blog-gnb .gnb_name {color:rgb(153, 153, 153);}\n#blog-gnb .bar {background:rgb(153, 153, 153);}\n#blog-gnb .btn_blog_login {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_login.png) no-repeat 0 0;}\n#blog-gnb .gnb_icon {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_menu.png) no-repeat 0 0 !important;}\n#blog-gnb .go-down {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_down.png);}\n#blog-gnb .gnb_my_namebox {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_down.png) no-repeat 100% 50% !important;}\n#blog-gnb .go-up {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_up.png);}\n#blog-gnb .gnb_lyr_opened .gnb_my_namebox {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_up.png) no-repeat 100% 50% !important;}\n\n* html #blog-gnb .btn_blog_login { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_login.png,sizingMethod=crop); }\n* html #blog-gnb .gnb_icon { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_menu.png,sizingMethod=crop); }\n* html #blog-gnb .go-down { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_down.png,sizingMethod=crop); }\n* html #blog-gnb .gnb_my_namebox { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_down.png,sizingMethod=crop); }\n* html #blog-gnb .go-up { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_up.png,sizingMethod=crop); }\n* html #blog-gnb .gnb_lyr_opened .gnb_my_namebox { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_up.png,sizingMethod=crop); }\n\n#foldset .go-left {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_left.png)}\n#foldset .go-right {background:url(https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_right.png)}\n\n* html #foldset .go-left { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_left.png,sizingMethod=crop); }\n* html #foldset .go-right { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/gnb2014/0014_right.png,sizingMethod=crop); }\n\n#body {width:982px; margin:0 auto; padding:0;}\r\nbody, #head-skin, #bottom-skin {background-position:50% 0;}\r\n#wrapper {width:966px; padding-top:8px;}\r\n#content-area {width:966px;}\n\n\n\n.itemfont, a.itemfont:link, a.itemfont:visited, a.itemfont:hover, a.itemfont:active {font-size:9pt;font-family:\xeb\x8f\x8b\xec\x9b\x80, \xea\xb5\xb4\xeb\xa6\xbc, seoul, verdana, arial;}\na.itemTagfont:link, a.itemTagfont:visited {font-size:9pt;font-family:\xeb\x8f\x8b\xec\x9b\x80, \xea\xb5\xb4\xeb\xa6\xbc, seoul, verdana, arial;}\na.itemTagfont:hover , a.itemTagfont:active {font-size:9pt;font-family:\xeb\x8f\x8b\xec\x9b\x80, \xea\xb5\xb4\xeb\xa6\xbc, seoul, verdana, arial; color:#418F21;}\n.itemSubjectfont   {font-size:9pt;font-family:\xeb\x8f\x8b\xec\x9b\x80, \xea\xb5\xb4\xeb\xa6\xbc, seoul, verdana, arial;}\n#post-area .post_adpost .itemSubjectfont {font-size:10pt !important;font-family:\xeb\x8f\x8b\xec\x9b\x80, \xea\xb5\xb4\xeb\xa6\xbc, seoul, verdana, arial;}\n\n\n#blog-profile .border {border-width:0px;border-style:solid;border-color:rgb(255, 255, 255);}\n\n#blog-profile .bg-head {height:0px;background:none;}\n\n#blog-profile .bg-body {padding:0px;background:none;}\n\n#blog-profile .bg-footer {height:0px;background:none;}\n\n#blog-profile .col {color:#444444;}\n\n#blog-profile .icon {background-image:url(https://blogimgs.pstatic.net/nblog/skins/profile/0162_icon.gif);}\n\n#blog-profile .image {display:block;}\n\n#blog-profile .image img {width:161px;}\n\n#blog-profile .align {text-align:left;}\n\n\n#blog-rss {height:27px;background-image:url(https://blogimgs.pstatic.net/nblog/skins/rss/0104_image_1.gif);}\n\n#blog-rss .rss1 {width:42px;height:14px;margin:8px 0 0 30px;}\n\n#blog-rss .rss2 {width:42px;height:14px;margin:8px 0 0 72px;}\n\n#blog-rss .rss3 {width:48px;height:14px;margin:8px 0 0 114px;}\n#blog-menu .border {height:60px;border-width:0px;border-color:rgb(0, 0, 0);border-style:dotted;}\n\n#blog-menu table {height:60px;background:url(https://ssl.pstatic.net/static/blog/skin/108/blog-menu.png);}\n\n#blog-menu .on {color:rgb(51, 51, 51);}\n\n#blog-menu .off {color:rgb(153, 153, 153);}\n\n#blog-menu .bar {background:rgb(153, 153, 153);}\n\n\n\n* html #blog-menu table { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://ssl.pstatic.net/static/blog/skin/108/blog-menu.png,sizingMethod=crop); }\n#post-area .post {border-width:0px;border-color:rgb(235, 235, 235);border-style:none;}\n\n#post-area .post-back {background:rgb(255, 255, 255);}\n\n#post-area .pcol1 {color:rgb(0, 0, 0);font-size:14px;}\n\n#post-area .pcol2 {color:rgb(68, 68, 68);}\n\n#post-area .pcol2b {background:rgb(68, 68, 68);}\n\n#post-area .cline {border-bottom-color:rgb(68, 68, 68);}\n\n#post-area .pcol3 {color:rgb(0, 0, 0);}\n\n#post-area .dline {border-top-width:1px;border-top-color:rgb(0, 0, 0);border-top-style:dotted;}\n\n#post-area .htl {width:15px;height:15px;background:none;}\n\n#post-area .htc {height:15px;background:none;}\n\n#post-area .htr {width:15px;height:15px;background:none;}\n\n#post-area .ftl {width:15px;height:15px;background:none;}\n\n#post-area .ftc {height:15px;background:none;}\n\n#post-area .ftr {width:15px;height:15px;background:none;}\n\n#post-area .bcl {width:15px;background:none;}\n\n#post-area .bcc {background:none;}\n\n#post-area .bcr {width:15px;background:none;}\n\n#post-area .ico1 {background:url(https://blogimgs.pstatic.net/nblog/skins/poststyle/0008_ico1_up.gif);}\n\n#post-area .ico2 {background:url(https://blogimgs.pstatic.net/nblog/skins/poststyle/0008_ico1_down.gif);}\n\n#post-area .ico3 {background:url(https://blogimgs.pstatic.net/nblog/skins/poststyle/0008_ico2.gif);}\n\n#post-area .comment {background:transparent;}\n\n#post-area .btn {background:url(https://blogimgs.pstatic.net/nblog/skins/poststyle/0000_input.png);}\n\n#post-area .btn-sympathy {background:url(https://blogimgs.pstatic.net/nblog/skins/poststyle/btn_sympathy_03.gif);}\n\n#post-area .btn_r {background:url(https://blogimgs.pstatic.net/nblog/skins/poststyle/btn_reply_default.gif);}\n\n\n\n* html #post-area .btn { background:transparent; filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src=https://blogimgs.pstatic.net/nblog/skins/poststyle/0000_input.png,sizingMethod=crop); }\n.post-back {background:rgb(255, 255, 255);}\n.pcol1 {color:rgb(0, 0, 0);font-size:14px;}\n.pcol2 {color:rgb(68, 68, 68);}\n.pcol2b {background:rgb(68, 68, 68);}\n.pcol3 {color:rgb(0, 0, 0);}\n.bcc {background:none;}\n#post-area .sline {border-bottom-color:rgb(0, 0, 0);}\n\n\r\n\t\r\n\t\r\n/*]]>*/\r\n</style>\r\n\r\n<script type="text/javascript" src="https://ssl.pstatic.net/t.static.blog/mylog/versioning//common/js/global/RemoveSubDomain-12d2f16_https.js"></script>\r\n<script>\r\n\r\n\r\n\r\n\r\n\r\n\r\nvar mylogURL = \'https://blog.naver.com\';\r\nvar adminURL = \'https://admin.blog.naver.com\';\r\nvar noteURL = \'https://note.naver.com\';\r\nvar itemURL = \'https://item.naver.com\';\r\nvar cafeURL = \'https://cafe.naver.com\';\r\nvar profileURL = \'https://blog.naver.com\';\r\nvar blogURL = \'https://blog.naver.com\';\r\nvar blogURLHttp = \'https://blog.naver.com\';\r\nvar prologueURL = \'https://blog.naver.com\';\r\nvar sectionURL = \'https://section.blog.naver.com\';\r\nvar memologURL = \'https://blog.naver.com\';\r\nvar lifeURL = \'https://lifelog.blog.naver.com\';\r\nvar uploadURL = \'https://upload.blog.naver.com\';\r\nvar imageURL = \'https://blogimgs.pstatic.net\';\r\nvar attachURL = \'https://blogfiles.pstatic.net\';\r\nvar thumbnailURL = \'https://blogthumb.pstatic.net\';\r\nvar nonCachedThumbnailURL = \'https://blogthumb.pstatic.net\';\r\nvar filetransURL = \'http://filetrans.blog.naver.com\';\r\nvar item2_bridgeURL = \'http://bridge.item2.naver.com\';\r\nvar idURL = \'http://nid.naver.com\';\r\nvar idURLSecret = \'https://nid.naver.com\';\r\nvar mapviewURL = \'http://mapview.naver.com\';\r\nvar exifURL = \'https://exif-blog.ssl.phinf.net\';\r\nvar viewerImageUrl = imageURL + "/blog20/blog/layout_photo/viewer/";\r\nvar domainURL = "";\r\nvar greenReviewCampaignURL = \'http://campaign.naver.com\';\r\nvar writeURL = \'https://blog.naver.com\';\r\nvar spiURL = \'https://ssl.pstatic.net/spi\';\r\nvar blogProfileThumbnailUrl=\'https://blogpfthumb-phinf.pstatic.net\';\r\nvar naverCommentStaticURL = \'https://ssl.pstatic.net/static.cbox\';\r\nvar naverCommentApiURL = \'https://apis.naver.com/commentBox/cbox9\';\r\nvar naverCommentApiProxyURL = \'https://apis.naver.com/commentBox/blogid\';\r\nvar itemImagesURL = \'https://blogimgs.pstatic.net/item\';\r\n\r\nvar sCssUrlForPhotoLayer = \'https://ssl.pstatic.net/t.static.blog/mylog/versioning//common/css/storyphoto_original_viewer-adf5d27_https.css\';\r\nvar commonStatDailyURL = \'https://blog.stat.naver.com\';\r\nvar baUrl = \'https://scv-blog.io.naver.com/jackpotlog/v1/logs\';\r\n\n\n\n\n\nvar blogId = \'bcf5qp11\' || \'bcf5qp11\';  \nvar userId = \'\'; \nvar userNo = \'\'; \nvar userNaverId = \'\';\nvar baUserKey = \'__UNKNOWN__\';\n\n\n\nvar isWritingBlocked = false;\nvar isWritingBlockedBySpamIP = false;\nvar isWritingBlockedBySpamIPManually = false;\nvar isLoggedIn = false;\nvar isShortestContentAreaWidth = false;\n\nvar blogOwner = false; \n\nvar blogNo = \'165273605\';\nvar nickName = \'\xec\x8a\xa4\xed\x94\xbc\xeb\x93\x9c \xec\x87\xbc\xed\x95\x91\';\nvar isInitializingBlog = false;\nvar rightClickOpenYn = false;\nvar isMylogBlocked = false;\nvar isBlogBlock = false;\nvar blockOrWriteBlock = false;\nvar autoSourcingYn = true;\n\n\nvar isMemolog = false;\nvar isMemologList = false;\nvar isPrologue = false;\n\n\nvar isBlogMe = false;\n\nvar isUsingUrl = false;\n\n\nvar isRequestFromIPad = false;\n\n\nvar isOverIOS5_0Version = false;\nvar isOverAndroidJellybeanVersion = false;\nvar isCommingNaverApp = false;\nvar isUsingNaverKitkatEngine = false;\nvar isAndroidKitkatVersion = false;\n\nvar defaultSmartEditorVersion = 2;\n\nvar adContentLocation = "-1";\n\n\n\r\n\r\n\r\n\r\nvar readOnlyStatus = false;\r\nvar readOnlyStatusAll = false;\r\nvar readOnlyLinkErrorMsg = \'\xec\xa3\x84\xec\x86\xa1\xed\x95\xa9\xeb\x8b\x88\xeb\x8b\xa4. \xeb\xb8\x94\xeb\xa1\x9c\xea\xb7\xb8 \xec\x84\x9c\xeb\xb9\x84\xec\x8a\xa4 \xec\xa0\x90\xea\xb2\x80 \xec\xa4\x91\xec\x9e\x85\xeb\x8b\x88\xeb\x8b\xa4. \\n\xec\xa0\x90\xea\xb2\x80 \xec\x8b\x9c\xea\xb0\x84 \xeb\x8f\x99\xec\x95\x88\xec\x9d\x80 \xea\xb8\xb0\xeb\x8a\xa5 \xec\x9d\xb4\xec\x9a\xa9\xec\x9d\xb4 \xec\xa0\x9c\xed\x95\x9c\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4. \\n\xec\x9e\x90\xec\x84\xb8\xed\x95\x9c \xeb\x82\xb4\xec\x9a\xa9\xec\x9d\x80 \xeb\xb8\x94\xeb\xa1\x9c\xea\xb7\xb8 \xed\x99\x88 \xea\xb3\xb5\xec\xa7\x80\xec\x82\xac\xed\x95\xad\xec\x9d\x84 \xec\xb0\xb8\xea\xb3\xa0\xed\x95\xb4\xec\xa3\xbc\xec\x84\xb8\xec\x9a\x94.\';\r\nvar readOnlyCommentMsg = \'12\xec\x9b\x94 17\xec\x9d\xbc(\xec\x9b\x94) \xec\x98\xa4\xec\xa0\x84 0\xec\x8b\x9c~8\xec\x8b\x9c \xec\x84\x9c\xeb\xb9\x84\xec\x8a\xa4 \xec\xa0\x90\xea\xb2\x80\xec\x9c\xbc\xeb\xa1\x9c \xeb\x8c\x93\xea\xb8\x80 \xec\x9e\x91\xec\x84\xb1\xec\x9d\xb4 \xec\xa0\x9c\xed\x95\x9c\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4. \\n\xeb\x8d\x94\xec\x9a\xb1 \xec\x95\x88\xec\xa0\x95\xec\xa0\x81\xec\x9d\xb8 \xec\x84\x9c\xeb\xb9\x84\xec\x8a\xa4\xeb\xa1\x9c \xec\xb0\xbe\xec\x95\x84\xeb\xb5\x99\xea\xb2\xa0\xec\x8a\xb5\xeb\x8b\x88\xeb\x8b\xa4. \xeb\xb6\x88\xed\x8e\xb8\xed\x95\x98\xec\x8b\x9c\xeb\x8d\x94\xeb\x9d\xbc\xeb\x8f\x84 \xec\xa1\xb0\xea\xb8\x88\xeb\xa7\x8c \xea\xb8\xb0\xeb\x8b\xa4\xeb\xa0\xa4\xec\xa3\xbc\xec\x84\xb8\xec\x9a\x94.\';\r\nvar sIsTagReadOnly = \'\';\r\nvar sTagSorryText = \'\xec\xa3\x84\xec\x86\xa1\xed\x95\xa9\xeb\x8b\x88\xeb\x8b\xa4. \xed\x83\x9c\xea\xb7\xb8 \xec\x84\x9c\xeb\xb9\x84\xec\x8a\xa4 \xec\xa0\x90\xea\xb2\x80 \xec\xa4\x91\xec\x9e\x85\xeb\x8b\x88\xeb\x8b\xa4.\\n\xec\xa0\x90\xea\xb2\x80 \xec\x8b\x9c\xea\xb0\x84 \xeb\x8f\x99\xec\x95\x88\xec\x9d\x80 \xec\x9d\xbc\xeb\xb6\x80 \xec\x84\x9c\xeb\xb9\x84\xec\x8a\xa4 \xec\x9d\xb4\xec\x9a\xa9\xec\x9d\xb4 \xec\xa0\x9c\xed\x95\x9c\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4.\\n\xec\x9e\x90\xec\x84\xb8\xed\x95\x9c \xeb\x82\xb4\xec\x9a\xa9\xec\x9d\x80 \xea\xb3\xb5\xec\xa7\x80\xec\x82\xac\xed\x95\xad\xec\x9d\x84 \xec\xb0\xb8\xec\xa1\xb0\xed\x95\x98\xec\x84\xb8\xec\x9a\x94.\';\r\nvar blogQuickPostingUseType = "NOT_SET"; \r\n\r\n\r\n\r\n\r\nvar isCommentReadOnly = false;\r\nvar sCommentReadOnlyBlockSubmit = \'\xec\xa3\x84\xec\x86\xa1\xed\x95\xa9\xeb\x8b\x88\xeb\x8b\xa4. \xeb\xb8\x94\xeb\xa1\x9c\xea\xb7\xb8 \xeb\x8c\x93\xea\xb8\x80, \xeb\x8b\xb5\xea\xb8\x80 \xec\x84\x9c\xeb\xb9\x84\xec\x8a\xa4 \xec\xa0\x90\xea\xb2\x80 \xec\xa4\x91\xec\x97\x90\xeb\x8a\x94 \xec\x9d\xb4\xec\x9a\xa9\xec\x9d\xb4 \xec\xa0\x9c\xed\x95\x9c\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4.\';\r\nvar sCommentReadOnlyWriteMsg = \'\xec\x84\x9c\xeb\xb9\x84\xec\x8a\xa4 \xec\xa0\x90\xea\xb2\x80\xec\x9c\xbc\xeb\xa1\x9c \xeb\x8c\x93\xea\xb8\x80 \xec\x9e\x91\xec\x84\xb1\xec\x9d\xb4 \xec\xa0\x9c\xed\x95\x9c\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4.\\n\xeb\x8d\x94\xec\x9a\xb1 \xec\x95\x88\xec\xa0\x95\xec\xa0\x81\xec\x9d\xb8 \xec\x84\x9c\xeb\xb9\x84\xec\x8a\xa4\xeb\xa1\x9c \xec\xb0\xbe\xec\x95\x84\xeb\xb5\x99\xea\xb2\xa0\xec\x8a\xb5\xeb\x8b\x88\xeb\x8b\xa4. \xeb\xb6\x88\xed\x8e\xb8\xed\x95\x98\xec\x8b\x9c\xeb\x8d\x94\xeb\x9d\xbc\xeb\x8f\x84 \xec\xa1\xb0\xea\xb8\x88\xeb\xa7\x8c \xea\xb8\xb0\xeb\x8b\xa4\xeb\xa0\xa4\xec\xa3\xbc\xec\x84\xb8\xec\x9a\x94.\';\r\n \r\n\r\n\r\n\r\n\r\n\r\n\r\nvar isJeagleDebug = false;\r\n\r\n\r\n\r\n\r\n\r\nvar skinId = "0";\r\nvar skinType = "C";\r\n\r\nvar isEnglish = "false";\r\n\r\nvar areaCode = "11B10101";\r\nvar weatherType = "0";\r\n\r\nvar currencySign = "ALL";\r\n\r\nvar listNumVisitor = \'5\';\r\nvar isVisitorOpen = true;\r\nvar isCategoryOpen = true;\r\nvar writingMaterialListType = \'1\'\r\nvar previewCalType = \'\';\r\n\r\n\r\n\r\nvar oExternalWidget = [];\r\n\r\n\r\nvar calType = "";\r\n\r\n\r\nvar curLog = \'https://blog.naver.com\';\r\nvar playerType = \'0\';\r\nvar playerDesign = \'1\';\r\n\r\n\r\nvar isCommentOpen = true;\r\nvar listNumComment = 5;\r\n\r\n\r\nvar isBuddyOpen = true;\r\n\r\n\r\n\r\nvar userSelectMenu = \'\';\r\n\r\n\r\nvar visitorgpData = \'\';\r\nvar vigitorSetUrl = \'\';\r\nvar vigitorPropUrl = \'/versioning//common/swf/Widget/visitorGP/VisitorGP-50a2c61.xml\';\r\nvar visitorgp_vars = {\r\n\tsetUrl    : vigitorSetUrl,\r\n\treq_url   : \'/NVisitorgp4Ajax.naver?blogId=\' + blogId,\r\n\tprop_url  : vigitorPropUrl,\r\n\tgraphType : visitorgpData,\r\n\tflashvars : function(){\r\n\t\treturn "req_url=" + this.req_url +"&prop_url=" + this.prop_url +"&graphType=" + this.graphType;\r\n\t},\r\n\theight    : 121\r\n};\r\n\r\n\r\n\r\nvar wat

In [44]:
df3 = dft['url'].apply(get_html)
df3.to_csv('blog_data/htmllist.csv')
df3

https://blog.naver.com//PostView.naver?blogId=hkh443&logNo=223750217199&redirect=Dlog&widgetTypeCall=true&topReferer=https%3A%2F%2Fblog.naver.com%2F&trackingCode=blog_etc&directAccess=false
https://blog.naver.com//PostView.naver?blogId=hprbel1097&logNo=223750429455&redirect=Dlog&widgetTypeCall=true&topReferer=https%3A%2F%2Fblog.naver.com%2F&trackingCode=blog_etc&directAccess=false
https://blog.naver.com//PostView.naver?blogId=hprbel1097&logNo=223750407473&redirect=Dlog&widgetTypeCall=true&topReferer=https%3A%2F%2Fblog.naver.com%2F&trackingCode=blog_etc&directAccess=false
https://blog.naver.com//PostView.naver?blogId=hprbel1097&logNo=223750377422&redirect=Dlog&widgetTypeCall=true&topReferer=https%3A%2F%2Fblog.naver.com%2F&trackingCode=blog_etc&directAccess=false
https://blog.naver.com//PostView.naver?blogId=hsh6566&logNo=223751314968&redirect=Dlog&widgetTypeCall=true&topReferer=https%3A%2F%2Fblog.naver.com%2F&trackingCode=blog_etc&directAccess=false
https://blog.naver.com//PostView.naver?blogId=hsh6566&logNo=223750984544&redirect=Dlog&widgetTypeCall=true&topReferer=https%3A%2F%2Fblog.naver.com%2F&trackingCode=blog_etc&directAccess=false
https://blog.naver.com//PostView.naver?blogId=hsh6566&logNo=223750871127&redirect=Dlog&widgetTypeCall=true&topReferer=https%3A%2F%2Fblog.naver.com%2F&trackingCode=blog_etc&directAccess=false
https://blog.naver.com//PostView.naver?blogId=hsh6566&logNo=223750315721&redirect=Dlog&widgetTypeCall=true&topReferer=https%3A%2F%2Fblog.naver.com%2F&trackingCode=blog_etc&directAccess=false
https://blog.naver.com//PostView.naver?blogId=lzheng&logNo=223750201349&redirect=Dlog&widgetTypeCall=true&topReferer=https%3A%2F%2Fblog.naver.com%2F&trackingCode=blog_etc&directAccess=false

0    \r\n\r\n\r\n\r\n\r\n<!DOCTYPE HTML PUBLIC "-//...
1    \r\n\r\n\r\n\r\n\r\n<!DOCTYPE HTML PUBLIC "-//...
2    \r\n\r\n\r\n\r\n\r\n<!DOCTYPE HTML PUBLIC "-//...
3    \r\n\r\n\r\n\r\n\r\n<!DOCTYPE HTML PUBLIC "-//...
4    \r\n\r\n\r\n\r\n\r\n\r\n<!DOCTYPE HTML PUBLIC ...
5    \r\n\r\n\r\n\r\n\r\n\r\n<!DOCTYPE HTML PUBLIC ...
6    \r\n\r\n\r\n\r\n\r\n\r\n<!DOCTYPE HTML PUBLIC ...
7    \r\n\r\n\r\n\r\n\r\n\r\n<!DOCTYPE HTML PUBLIC ...
8    \r\n\r\n\r\n\r\n\r\n\r\n<!DOCTYPE HTML PUBLIC ...
Name: url, dtype: object

In [51]:
df4 = df3.apply(get_href)
df4.to_csv('blog_data/itemlist.csv')
df4

18
href : https://vvd.bz/jEV
{'Date': 'Fri, 07 Feb 2025 08:24:51 GMT', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir :
href : https://vvd.bz/jEY
{'Date': 'Fri, 07 Feb 2025 08:24:54 GMT', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir :
href : https://vvd.bz/jEy
{'Date': 'Fri, 07 Feb 2025 08:24:57 GMT', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir :
href : https://vvd.bz/jEw
{'Date': 'Fri, 07 Feb 2025 08:24:58 GMT', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir :
href : https://vvd.bz/jEb
{'Date': 'Fri, 07 Feb 2025 08:25:00 GMT', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir :
href : https://vvd.bz/jEd
{'Date': 'Fri, 07 Feb 2025 08:25:03 GMT', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir :
href : https://vvd.bz/jEd
 - redir :
href : https://vvd.bz/jEf
{'Date': 'Fri, 07 Feb 2025 08:25:07 GMT', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir :
href : https://vvd.bz/jEm
{'Date': 'Fri, 07 Feb 2025 08:25:09 GMT', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir :
href : https://kream.co.kr/products/403439
 - redir :
href : https://vvd.bz/eZe
{'Date': 'Fri, 07 Feb 2025 08:25:22 GMT', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir :
href : https://vvd.bz/jEn
{'Date': 'Fri, 07 Feb 2025 08:25:24 GMT', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir :
href : https://vvd.bz/jEo
{'Date': 'Fri, 07 Feb 2025 08:25:27 GMT', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir :
href : https://vvd.bz/jEp
{'Date': 'Fri, 07 Feb 2025 08:25:29 GMT', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir :
href : https://vvd.bz/jEp
{'Date': 'Fri, 07 Feb 2025 08:25:31 GMT', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir :
href : https://vvd.bz/jEq
{'Date': 'Fri, 07 Feb 2025 08:25:34 GMT', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir :
href : https://vvd.bz/jEv
{'Date': 'Fri, 07 Feb 2025 08:25:37 GMT', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': 'frame-ancestors *', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'Accept-CH': 'Sec-CH-UA-Model', 'Permissions-Policy': 'ch-ua-model=(self "https://vvd.bz")', 'Referrer-Policy': 'unsafe-url', 'Alt-Svc': 'h3=":443"; ma=86400'}
 - redir :
href : https://bit.ly/3Xa0U12
{'Server': 'nginx', 'Date': 'Fri, 07 Feb 2025 08:25:40 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '86', 'Cache-Control': 'private, max-age=90', 'Content-Security-Policy': 'referrer always;', 'Location': 'https://link.coupang.com/a/bEzTRc', 'Referrer-Policy': 'unsafe-url', 'Set-Cookie': '_bit=p178pE-6f21fb4ea34c3216be-00u; Domain=bit.ly; Expires=Wed, 06 Aug 2025 08:25:40 GMT', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'}
 - redir : https://link.coupang.com/a/bEzTRc
{'Server': 'istio-envoy', 'x-ua-compatible': 'IE=edge', 'Cache-Control': 'no-store, no-cache, must-revalidate', 'x-robots-tag': 'noindex, nofollow, noindex, nofollow', 'Location': 'https://www.coupang.com/np/search?q=%EB%93%9C%EB%A6%BC%ED%8C%9C%20%ED%94%8C%EB%A3%A8%EC%84%9C&src=1139000&spec=10799999&addtag=200&ctag=%EB%93%9C%EB%A6%BC%ED%8C%9C%20%ED%94%8C%EB%A3%A8%EC%84%9C&lptag=AF9131142&itime=20250207172543&pageType=SEARCH&pageValue=%EB%93%9C%EB%A6%BC%ED%8C%9C%20%ED%94%8C%EB%A3%A8%EC%84%9C&wPcid=17389167439950940689012&wRef=&wTime=20250207172543&redirect=landing&traceid=V0-181-3037f76c0117c9b5&mcid=30b0b823ea0d4481b36f126eccb81245&placementid=&campaignid=&contentcategory=&imgsize=&tsource=&pageid=&deviceid=&token=&contenttype=&subid=&impressionid=&campaigntype=&requestid=&contentkeyword=&subparam=', 'Content-Language': 'ko', 'x-envoy-upstream-service-time': '3', 'x-envoy-decorator-operation': ':0/*', 'Content-Length': '0', 'Date': 'Fri, 07 Feb 2025 08:25:44 GMT', 'Connection': 'keep-alive', 'Set-Cookie': 'member_srl=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/, SAID=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/; HttpOnly, PCID=17389167439947857702765; Max-Age=315360000; Expires=Mon, 05 Feb 2035 08:25:43 GMT; Domain=coupang.com; Path=/, MARKETID=17389167439947857702765; Secure; HttpOnly; SameSite=None; Expires=Wed, 06-Feb-2030 17:25:43 KST; Domain=.coupang.com; Path=/, member_srl=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/, SAID=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/; HttpOnly, PCID=17389167439950940689012; Max-Age=315360000; Expires=Mon, 05 Feb 2035 08:25:43 GMT; Domain=coupang.com; Path=/, MARKETID=17389167439947857702765; Secure; HttpOnly; SameSite=None; Expires=Wed, 06-Feb-2030 17:25:43 KST; Domain=.coupang.com; Path=/, trac_src=1139000; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:25:43 GMT; Domain=coupang.com; Path=/, trac_spec=10799999; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:25:43 GMT; Domain=coupang.com; Path=/, trac_addtag=200; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:25:43 GMT; Domain=coupang.com; Path=/, trac_ctag=%EB%93%9C%EB%A6%BC%ED%8C%9C+%ED%94%8C%EB%A3%A8%EC%84%9C; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:25:43 GMT; Domain=coupang.com; Path=/, trac_lptag=AF9131142; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:25:43 GMT; Domain=coupang.com; Path=/, trac_itime=20250207172543; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:25:43 GMT; Domain=coupang.com; Path=/, _abck=CCD77CF2ABDE1047F1E470F50694408A~-1~YAAQniE1FxRj8bKUAQAAfsuD3w1FUkGaMWSC8Ef36hUvWC68GNlZa6uZFB9NrR21uN9jVPPSORXRhM4lnpq41PvLh+QYBBXLmGAWpHLRtxchfSyCEBGke9odYeJr+PDocjHepUs+k/h6Zb13pRztVwC4UeUK1icTY0W+xVld7+IttfE68BjTzpUcLI0psfk3HZQJ+imQ9KkwHlgPPmIm4N2XXUfU9VN/c7LBD4IENquKIuC7NgtID7o90AoSotzJhhMOHMohAT75CUknOglIstyaN3x+vy3/44I8FSqlEOpvMv1EgDQ7Z8dB3c5KT+EAHppaEBewFXovTesqdUOAAAABBM46e60G4EA/DaEOtC7ZW5IA8vRI43kfXqKSK+bVNXF5eaLiP99S0VIHTxTNOcyq5IHDJK96FG4JQvs=~-1~-1~-1; Domain=.coupang.com; Path=/; Expires=Sat, 07 Feb 2026 08:25:44 GMT; Max-Age=31536000; Secure, bm_sz=BB2B6A727EA103988410668CC097E829~YAAQniE1FxVj8bKUAQAAfsuD3xq1C5YieODbKxnZ5YFq3K8+zO3DqmJKxQUB2iv1PlVE26VDflybvJmqXuukILn/Pmrr0/qrkcQBTE505EPbvLxwBFWOMmeVOB1EPK+twtg8ZLrsww95AIyqYllbls7WFMzKpEB4dSbvbUph2/aBXd54M02Lb9QVYVXFs3OLYeiM3755CbCoI/LvCpXKxALpCELKzO4DVVgruiOJJnXC4+wzCcaF6EKZ6qNfwpT5otU9CeOtZwNMS6gr/VDYAzrEGmphOpHCH843qfY93MHsOpWNA9aFHonSyuyNLsOAI3sC+EnqJu32dvixe+E2JCqf8cA8lxlIpM3thrng2w==~3420994~3294531; Domain=.coupang.com; Path=/; Expires=Fri, 07 Feb 2025 12:25:43 GMT; Max-Age=14399', 'Strict-Transport-Security': 'max-age=31536000'}
5
href : https://bit.ly/412Qr9b
{'Server': 'nginx', 'Date': 'Fri, 07 Feb 2025 08:25:47 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '86', 'Cache-Control': 'private, max-age=90', 'Content-Security-Policy': 'referrer always;', 'Location': 'https://link.coupang.com/a/cdp3s3', 'Referrer-Policy': 'unsafe-url', 'Set-Cookie': '_bit=p178pL-40f4e63d2091d2b9ab-00N; Domain=bit.ly; Expires=Wed, 06 Aug 2025 08:25:47 GMT', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'}
 - redir : https://link.coupang.com/a/cdp3s3
{'Server': 'istio-envoy', 'x-ua-compatible': 'IE=edge', 'Cache-Control': 'no-store, no-cache, must-revalidate', 'x-robots-tag': 'noindex, nofollow, noindex, nofollow', 'Location': 'https://www.coupang.com/np/search?q=Gucci%20Gloves%20Pink&src=1139000&spec=10799999&addtag=200&ctag=Gucci%20Gloves%20Pink&lptag=AF3408489&itime=20250207172549&pageType=SEARCH&pageValue=Gucci%20Gloves%20Pink&wPcid=17389167496268726431108&wRef=&wTime=20250207172549&redirect=landing&traceid=V0-181-32ee62f51a855c39&mcid=bc9d7d34d9c34a2c92bd5c3339e44125&placementid=&campaignid=&contentcategory=&imgsize=&tsource=&pageid=&deviceid=&token=&contenttype=&subid=&impressionid=&campaigntype=&requestid=&contentkeyword=&subparam=', 'Content-Language': 'ko', 'x-envoy-upstream-service-time': '3', 'x-envoy-decorator-operation': ':0/*', 'Content-Length': '0', 'Date': 'Fri, 07 Feb 2025 08:25:49 GMT', 'Connection': 'keep-alive', 'Set-Cookie': 'member_srl=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/, SAID=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/; HttpOnly, PCID=17389167496248402841571; Max-Age=315360000; Expires=Mon, 05 Feb 2035 08:25:49 GMT; Domain=coupang.com; Path=/, MARKETID=17389167496248402841571; Secure; HttpOnly; SameSite=None; Expires=Wed, 06-Feb-2030 17:25:49 KST; Domain=.coupang.com; Path=/, member_srl=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/, SAID=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:10 GMT; Domain=coupang.com; Path=/; HttpOnly, PCID=17389167496268726431108; Max-Age=315360000; Expires=Mon, 05 Feb 2035 08:25:49 GMT; Domain=coupang.com; Path=/, MARKETID=17389167496248402841571; Secure; HttpOnly; SameSite=None; Expires=Wed, 06-Feb-2030 17:25:49 KST; Domain=.coupang.com; Path=/, trac_src=1139000; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:25:49 GMT; Domain=coupang.com; Path=/, trac_spec=10799999; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:25:49 GMT; Domain=coupang.com; Path=/, trac_addtag=200; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:25:49 GMT; Domain=coupang.com; Path=/, trac_ctag=Gucci+Gloves+Pink; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:25:49 GMT; Domain=coupang.com; Path=/, trac_lptag=AF3408489; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:25:49 GMT; Domain=coupang.com; Path=/, trac_itime=20250207172549; Max-Age=86400; Expires=Sat, 08 Feb 2025 08:25:49 GMT; Domain=coupang.com; Path=/, _abck=CDF9E335694C7507F51392F1AD9CD131~-1~YAAQjyE1F1fA/qyUAQAAouGD3w3XyftyZvVmmL5eZElFZa7qbptFsPxzy44Ao38nVMpgpNGrr/cbJv2/Wa/GBnP8Vrsr88OsmVtlVOJqDHrp2RfAIq7OUk0IO2lG+QyLcoMGD3dmV/+zdsO6UDk6s0E8qlrhDrOi0Fi+KtJVuQgrSdfRBDkxwU0zcbsBeWgA06TTGkG8xGblin671tQKdcCMS06n5MYoIETkqnGwQBhsOPoPda2NrcU9BlLoD6QDpgQrLKx73vb6UHoqM8Zny9l1P4DejjnPb9CgeMzpr3nFpqHX9jTKiQEA3cI+T94kw2H8UllFBMG61qWXWZNfsK2kXLJqPoQmtNp9zIP0s2jLRyGc9nhUVsLNpuRnmiYT8B+2t5+UfIQn0dKg11wmo5skg5d2VcMf2sY/0XA=~-1~-1~-1; Domain=.coupang.com; Path=/; Expires=Sat, 07 Feb 2026 08:25:49 GMT; Max-Age=31536000; Secure, bm_sz=5F1412814FB65808A146880FBB469AE9~YAAQjyE1F1jA/qyUAQAAouGD3xpVH05jzTr3+uM+QGVGbdd18JUw+dQ2qtTUS1eQ7SCAoYiumGp2kouOoWOzxIG1pevf/MIS5wnlP8txvhhrvfwshyVs2WOL4VFR9MuAMhwLmU/jm2FZXxN9EB3jVOqJY0IrCLy7uTDmIXUu/Thh7U8IRgpOrRwqgMxa9L0O7KqxBM5sX9PhKC27T/0VUkkgLeOFjkKIOmAySu2tl02DzvRjg94Qi1Gjq87cSi2AnnGWuvucivXVcSFmYD1bGDZE6626BZJFcBGP7cvmwiU4fIjnDqxPqcI/M6pzAHYFGW00mQ47s/9v0FtUwyA/dwRsLhSitx5U8NVxicf9BQ==~4538936~3552309; Domain=.coupang.com; Path=/; Expires=Fri, 07 Feb 2025 12:25:49 GMT; Max-Age=14400', 'Strict-Transport-Security': 'max-age=31536000'}
href : https://bit.ly/42LuVau
{'Server': 'nginx', 'Date': 'Fri, 07 Feb 2025 08:25:51 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '86', 'Cache-Control': 'private, max-age=90', 'Content-Security-Policy': 'referrer always;', 'Location': 'https://link.coupang.com/a/cdp4Gl', 'Referrer-Policy': 'unsafe-url', 'Set-Cookie': '_bit=p178pP-9653ab0e9e324627a1-00W; Domain=bit.ly; Expires=Wed, 06 Aug 2025 08:25:51 GMT', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'}
 - redir : https://link.coupang.com/a/cdp4Gl

KeyboardInterrupt: